feat: Support SubscribeTopicEvents API
mosn/layotto pull request #1088
Opened 2024-12-09 13:40 UTC by CrazyHZM

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-12-14 03:56 UTC, CrazyHZM commented on pkg/grpc/default_api/api.go
> +		//closeCh:                  make(chan struct{}),
暂时先去掉

2024-12-16 08:36 UTC, wenxuwan requested changes

2024-12-16 08:36 UTC, wenxuwan commented on pkg/grpc/default_api/api.go
> +	wg   sync.WaitGroup
这个a.wg.Add了两次，done了两次，wg.wait()没有，没什么用吧？

2024-12-16 08:36 UTC, wenxuwan commented on pkg/grpc/default_api/api_subscribe.go
> +	var wg sync.WaitGroup
这个地方没必要起个wg吧，下面的for已经是个循环了，起个goroutine没必要在外面等待，本身也不会做任何的收尾

2024-12-16 08:36 UTC, wenxuwan commented on pkg/grpc/default_api/api_subscribe.go
> +	err := conn.stream.Send(&runtimev1pb.SubscribeTopicEventsResponse{
这里如果发失败了，ctx没有cancel或者超时下面的select就阻塞了

2024-12-17 03:44 UTC, wenxuwan approved these changes

2024-12-17 03:44 UTC, merged