Zookeeper lock
mosn/layotto pull request #111
Opened 2021-07-03 10:34 UTC by ZLBer

**What this PR does**:

add zookeeper lock

**Which issue(s) this PR fixes**: 

Fixes #104

**Special notes for your reviewer**:

@seeflood 

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-07-04 03:16 UTC, zhenjunMa commented
@ZLBer thanks for your contribute!

could you please add a quickstart for this component? such as a `zk_lock.json` and some clients to lock/unlock?

2021-07-04 04:43 UTC, seeflood commented
恩恩 目前的代码只实现了组件部分，其实还需要一些细碎的配套工作，包括在layotto的main里注册组件，demo（client、config.json)，文档，这些工作量不大但是很有必要

稍等哈我在写《组件开发指南》，描述下有哪些配套工作

2021-07-04 09:50 UTC, ZLBer commented
@zhenjunMa @seeflood  fine, i will add a  quickstart  after  the guide book is  finished.

2021-07-05 10:15 UTC, seeflood commented
@ZLBer Hi, I just added a developer guide.See https://github.com/mosn/layotto/blob/main/docs/zh/development/developing-component.md

Please improve this pr according to the guide.
Thanks for your passion!

2021-07-06 04:02 UTC, seeflood commented
@ZLBer  我在《组件开发者指南》中补充了单元测试的mock方法，供参考~
![image](https://user-images.githubusercontent.com/26001097/124540439-f93a5900-de51-11eb-8871-abf506bf762d.png)

2021-07-06 15:07 UTC, seeflood commented
有几个问题抛出来讨论下：
1. 关于如何写zk的ut：zk的sdk返回的zk.Conn是个struct，这个sdk设计的不太好，我们可以把他封装成一个interface
我看了下Dapr的zookeeper组件的写法也是这种思路，可以参考https://github.com/dapr/components-contrib/tree/master/state/zookeeper
![image](https://user-images.githubusercontent.com/26001097/124621883-37b13180-dead-11eb-9483-853639ec5ea6.png)

2. 目前每次TryLock是重新和zk建立连接，我理解其实初始化的时候建立一次连接就够了、这个连接可以一直复用吧？（同样可以参考上面的链接）
![image](https://user-images.githubusercontent.com/26001097/124622017-51527900-dead-11eb-883a-b2e7d2cb87ef.png)

3. 在继续改代码之前，我们可能要先想清楚一个设计上的问题、免得等会返工：下面这个特殊场景如何处理?
app tryLock 声明10秒过期，调用成功
![image](https://user-images.githubusercontent.com/26001097/124622604-d9388300-dead-11eb-80e5-b38073ad86aa.png)
sidecar和zk服务器之间网络抖动/网络故障连不上了，临时节点被自动删除
![image](https://user-images.githubusercontent.com/26001097/124623005-2ae10d80-deae-11eb-9358-766531e33df5.png)
由于临时节点已经被删除，此时sidecar2抢同一把锁，抢锁成功：
![image](https://user-images.githubusercontent.com/26001097/124623695-c4102400-deae-11eb-9730-0ceafb2d29f1.png)
于是，同一时刻有两个app有同一把锁，出现了正确性问题
会不会出现这种情况呢？如果会的话我们能否避免、应该怎么避免这种问题？

我要想想，先去看下zk客户端是咋实现锁的

2021-07-06 16:18 UTC, ZLBer commented
1.我也想过,要加mock的话只能加一层interface封装。

2.为什么不复用连接?  一开始想的是， 为了保证在任何情况下，都可以释放锁， 依赖于临时节点和connection的生命周期保持一致，所以需要connection和每次请求保持一致，但复用好像也不存在错误的情况？ 
 
3. 我想了一下，可以设置sessionTimeout=expireTime来避免这种情况，` The provided session timeout sets the amount of time for which a session is considered valid after losing connection to a server`, 即在expireTime时间内，即使发生网络抖动，server也不会去删除临时节点，保证在expireTime时间内锁的独占。那这也会导致没法复用连接(每次新建connection都要传sessionTimeout)

2021-07-07 15:32 UTC, seeflood commented
> 3. 我想了一下，可以设置sessionTimeout=expireTime来避免这种情况，` The provided session timeout sets the amount of time for which a session is considered valid after losing connection to a server`, 即在expireTime时间内，即使发生网络抖动，server也不会去删除临时节点，保证在expireTime时间内锁的独占。那这也会导致没法复用连接(每次新建connection都要传sessionTimeout)
>    zk实现的锁更多是顺序节点实现的阻塞锁吧，不符合这边的语义

恩恩，不管是阻塞锁还是非阻塞锁，其实都有这个带锁故障问题，我理解zk是靠session timeout解决的，但是这东西是每个连接固定好了的，不能复用连接、每次请求改timeout值

这个问题本质上是：api定义成了要求超时时间任意，但是zk（不开启ttl节点功能的话）不能任意。

那么推理一下我们有以下几种选择：

![image](https://user-images.githubusercontent.com/26001097/124787729-4fef8200-df7b-11eb-95a7-ee53f29eaf2d.png)

Life is hard,and defining API is harder!

2021-07-07 15:36 UTC, seeflood commented
所以如果我们想追求复用连接的话，那么有两条路：

方案c.复用连接，tryLock后起个定时任务删节点
实际ttl=session timeout  or 定时任务ttl
(取决于定时任务有没有执行失败)
这样就能解决问题了。虽然他不完美，但分布式锁本来就没法保证100%正确性


方案d. 改API，不要传什么ttl了

2021-07-07 16:49 UTC, seeflood commented
这几种方案里面我更倾向于A方案，每次来请求就新建个连接。
如果用户在意性能，那就把ttl node配置打开，组件用ttl node

明天讨论下

2021-07-07 17:36 UTC, seeflood commented
## 为什么redis实现这个API简单，为什么zk实现这个API这么复杂，复杂度来源于哪？
本质上是因为：TTL是个好东西，如果server端支持TTL，那么多个节点之间不需要做状态同步、故障检测，反正故障的时候server来自动删除锁，app和sidecar啥也不用管，就是俩无状态节点，偷懒美滋滋；

而如果server端不支持TTL，我们就要做多个有状态节点（app、sidecar、server)之间的状态同步、可靠故障检测，就有了上面这些问题

（zk原生sdk里的锁，本质上是帮用户实现了这些状态同步、故障检测）

## 分布式锁防止死锁的两种模式

a. 基于server TTL 的无状态架构

b. 基于节点之间状态同步、故障检测的有状态架构

如果选择了a,那么app端不需要sdk，直接用grpc api就行

如果选择了b，那么app端必然有逻辑，必然要开发sdk，想做到app不依赖sdk、直接用grpc api不现实（除非它自己实现sdk的逻辑）

## 后续API的演进方向

我们后面要加阻塞锁Lock(),其实也可以弄两种API,LockWithTTL(key,expire)和Lock(key)

想不依赖sdk的，调LockWithTTL；愿意依赖sdk的，调Lock

2021-07-08 02:39 UTC, ZLBer commented
@seeflood 
我看了下curator实现lock的文档，发现他们也没主动去解决问题3，而是建议用户自己去主动处理
https://curator.apache.org/curator-recipes/shared-reentrant-lock.html
![image](https://user-images.githubusercontent.com/20033804/124852282-aa69fc00-dfd6-11eb-8866-e71931cc04c9.png)
或许方案a 可以现在sidecar本地做下限制，尽量减少connection的建立。 

所以我们现阶段先采用哪个方案呢？

2021-07-08 04:46 UTC, seeflood commented
@ZLBer 我理解其实方案a和方案c的差别只是复用连接。方案a也要考虑上面的定时任务删除失败了怎么重试
（我下午看下zk go sdk的实现，看看调conn.Delete如果失败了 sdk能否帮我们重试）

所以我个人倾向于选择c方案+允许通过ttl node来实现
你可以看下c方案好写么，如果觉得不太好写也不要紧，可以先写ttl node；或者先写a方案,以后再优化

2021-07-08 04:56 UTC, seeflood commented
关于api演进的一种思路，供讨论：
后续grpc API都带上ttl，这样用户用grpc直接调的话，传ttl可以直接调，不需要考虑复杂的特殊场景；
app侧可以封装个sdk，用户调用的时候不需要传ttl，sdk自动帮忙做续租等操作

![image](https://user-images.githubusercontent.com/26001097/124864454-7ea54100-dfeb-11eb-9b64-350b33c2067b.png)

2021-07-08 08:59 UTC, ZLBer commented
@seeflood  
我怎么感觉方案c和方案a存在差别呢，正确性的问题，就是之前关于问题3，例如A节点网络发生抖动，导致连接断开，方案a在expire时间后关闭connection，方案c在sesisontimeout时间后关闭。如果sessiontimeout远小于expire，那么另一个节点B节点就会占据锁，而对A节点的承诺的expire时间没有达到且A也没有主动释放，但A的锁没了，A还在执行，B也在执行，出错。
你的意思是暂时不考虑这种情况吗？  
我的想法是可以先保证正确性，其次才是效率，比如连接复用。

2021-07-08 09:17 UTC, seeflood commented
>我的想法是可以先保证正确性，其次才是效率，比如连接复用。
同意！
@ZLBer 
我想了一下，你说的对，如果用户用粗粒度锁（任务执行的很慢，expire时间设置的很长，比session_timeout长多了）方案c可能导致session_timeout后就被别的机器抢锁了，而方案a能避免这个问题

我本来想干脆不管这种情况了，是因为看zk的文档，说zk server有配置、限制session_timeout的范围。但是确实方案a对于”粗粒度锁"的正确性保证更好一些，那就方案a+ttl node好了，性能问题我们倒是可以通过连接池优化

2021-07-08 10:26 UTC, seeflood commented
补充一下，关于a方案性能问题的思考：我们后续可以优化成连接池（现在先不用管）
比如连接池里有：timeout是5s的连接，timeout是10s的连接，timeout是15s的连接
这样一个请求来了,expire是4s，我们可以把timeout是5s的连接拿出来用
这样的话，新起定时任务，是在4s后调delete删除节点，而不是在4s后调close关闭连接（因为连接允许并发复用，用完了要放回连接池）
那么在定时任务delete删节点的时候，得保证这次delete执行失败后，有重试机制（不然就会有我上面说的问题，定时任务删除失败，但是心跳没断，发生死锁）
这就要看下zk的sdk实现，看看调delete的时候有没有帮我们做重试

当然这些以后做性能优化的时候再说

2021-07-08 17:25 UTC, ZLBer commented
@seeflood  
按照方案a 提交了一版代码，增加了一层interface，增加了mock测试

2021-07-09 01:10 UTC, seeflood requested changes

2021-07-09 01:10 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	if err != nil {
这里err应该有很多种可能，比如网络连接问题？需要判断下：
如果是锁过期了，那么返回response,nil
如果是其他err，要把err返回出去。上层看到有err会封装grpc结果

2021-07-09 01:10 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	NewConnection(expire time.Duration, meta metadata) (ZKConnection, error)
这里newConnection套了几层、且ZKConnection自己也能NewConnection  读起来有点绕
是否可以优化下？比如NewConnection 抽出一个ConnectionFactory interface，ZookeeperLock肚子里放一个ConnectionFactory

2021-07-12 03:58 UTC, seeflood requested changes

2021-07-12 03:58 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	conn, _, err := zk.Connect(meta.hosts, expire*time.Second, zk.WithLogger(defaultLogger{}))
这里expire已经是time.Duration了，不需要再乘以time.Second啦

2021-07-12 03:58 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	m.sessionTimeout = defaultSessionTimeout
关于时间处理的Tips：如果某个变量的类型是time.Duration，那开发者会默认它的单位是Nanosecond，所以如果往time.Duration里存东西，要转化成Nanosecond,比如写 2*time.Second这样
举个例子，可以看下redis实现lock的代码，
![image](https://user-images.githubusercontent.com/26001097/125228481-63964200-e307-11eb-9edd-79f18f113668.png)
![image](https://user-images.githubusercontent.com/26001097/125228562-93dde080-e307-11eb-9eed-01920e9ea605.png)

2021-07-12 03:58 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +		m.sessionTimeout = time.Duration(parsedVal)
这里也是时间单位问题，同上
		m.sessionTimeout =time.Duration(parsedVal) *time.Second

2021-07-12 06:23 UTC, seeflood requested changes

2021-07-12 06:23 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	zkConn, err := p.factory.NewConnection(p.metadata.sessionTimeout*time.Second, p.metadata)
这里也有时间单位问题，问题描述见下

2021-07-12 06:23 UTC, seeflood commented on docs/zh/component_specs/lock/zookeeper.md
> +示例：configs/config_lock_zookeeper.json
棒呀有文档了，这个文档可以也搞个英文版么~
一般就是google translate一下 改改病句即可

2021-07-12 06:23 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
这里新建一个logger、让zk的logger失灵的目的是啥？
因为日志可以帮助排查线上问题，如果让日志失灵了不好查问题呀

2021-07-13 02:42 UTC, ZLBer commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
打日志太频繁了..我还是打开吧

2021-07-13 03:20 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
> 打日志太频繁了..我还是打开吧。

如果想少打日志，可以改sdk的logInfo这个配置项~我翻了下zk sdk的代码，这个配置false的时候只打error日志：
![image](https://user-images.githubusercontent.com/26001097/125384862-1d56e680-e3cc-11eb-9302-d784b9680805.png)
可以给我们的组件加个配置项，允许用户配logInfo，非必填~

2021-07-13 03:23 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
> 这里需要用mosn的logger来接管吗

这个细节好，我们之前实现其他组件的时候都没注意这个……
最好用mosn的logger接管，因为用户可能对mosn的logger做了一些配置，比如日志打印的路径之类的，接管了之后可以把日志放到同一个地方
不过这个sdk的logger interface没区分error还是info，有点讨厌，我看下代码想想咋搞

2021-07-13 03:49 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
要不就先用mosn的logger接管，都打info日志，如何？
后面我们给zk的sdk提个pr 支持info和error等不同级别的日志

2021-07-13 03:51 UTC, ZLBer commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
那我先简单加个配置项了

2021-07-13 03:52 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +func (defaultLogger) Printf(format string, a ...interface{}) {
好

2021-07-13 06:15 UTC, seeflood commented
@ZLBer  CI流程里校验格式化没通过~
你在项目目录下敲：

```
go fmt ./...
```
然后git提交下有改动的东西即可

2021-07-13 06:23 UTC, seeflood requested changes

2021-07-13 06:23 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +	defaultSessionTimeout = 5
这里应该是：
defaultSessionTimeout = 5*time.Second
对吧？不然下面的直接赋值有问题
m.sessionTimeout = defaultSessionTimeout

2021-07-13 06:54 UTC, seeflood requested changes

2021-07-13 06:54 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +		return &lock.UnlockResponse{}, err
这里直接return &lock.UnlockResponse{}有个小问题，新创建的UnlockResponse肚子里的Status是0，代表成功
虽然上层看到有err就不会关注UnlockResponse了，但Status是SUCCESS还是有些奇怪~

所以可以改成：
a. return nil,err
b. return &lock.UnlockResponse{Status:INTERNAL_ERROR }, err

两种都行，看你喜欢~

2021-07-13 06:54 UTC, seeflood commented on components/lock/zookeeper/zookeeper_lock.go
> +			return &lock.UnlockResponse{}, err
同上

2021-07-13 06:56 UTC, seeflood commented
另外就是文档侧边栏需要加上~等会合并进这个pr后，我来加吧，怪我没写到贡献指南里
![image](https://user-images.githubusercontent.com/26001097/125405573-7766a480-e3ea-11eb-978c-d7e9e19a6d42.png)

2021-07-13 07:29 UTC, ZLBer commented
@seeflood 
侧边栏也改了  辛苦~

2021-07-13 08:59 UTC, seeflood commented
这个pr厉害了，升级golang/mock包后，发现了以前的configuration api相关的ut错误
我来看下

2021-07-13 13:28 UTC, merged

2021-07-13 13:29 UTC, seeflood commented
Thanks again for your contribution!