Add oss support
mosn/layotto pull request #118
Opened 2021-07-06 04:54 UTC by wenxuwan

**What this PR does**:

Add oss support, now only support file put and get.

**Which issue(s) this PR fixes**:

2021-07-06 04:55 UTC, wenxuwan commented
ut will add latter....

2021-07-12 13:31 UTC, wenxuwan commented
> ut will add latter....

ut done now.

2021-07-16 02:43 UTC, seeflood requested changes

2021-07-16 02:43 UTC, seeflood commented on docs/en/design/file/oss-design.md
> +####Put interface
这篇文档里很多####后面没空格，导致markdown渲染不出来~可以点预览看下哈

2021-07-16 02:43 UTC, seeflood commented on docs/zh/_sidebar.md
> +    - [OSS设计文档](zh/design/file/oss-design.md)
zh/design/file/oss-design.md
这个没提交哈

2021-07-16 02:43 UTC, seeflood commented on docs/en/design/file/oss-design.md
> +OSS Design Doc
这篇文档感觉是API介绍文档，要不挪下目录，当接口文档？
设计文档没有就算了，因为从重要程度上 给用户看的文档(quickstart、接口文档、组件文档）>给contributor看的文档（设计文档）

英文接口文档的目录 docs/en/api_reference/
中文接口文档的目录 docs/zh/api_reference/

对应的官网文档会展示在https://mosn.io/layotto/#/zh/api_reference/actuator/actuator

2021-07-16 02:45 UTC, wenxuwan commented on docs/zh/_sidebar.md
> +    - [OSS设计文档](zh/design/file/oss-design.md)
done

2021-07-16 02:57 UTC, wenxuwan commented on docs/en/design/file/oss-design.md
> +OSS Design Doc
done

2021-07-16 02:57 UTC, wenxuwan commented on docs/en/design/file/oss-design.md
> +####Put interface
done

2021-07-16 03:45 UTC, seeflood requested changes

2021-07-16 03:45 UTC, seeflood commented on demo/file/client.go
> +	//分片上传，片最小为100kb
中文注释改成英文吧

2021-07-16 03:45 UTC, seeflood commented on demo/file/client.go
> +		// 控制条件,根据实际调整
同上

2021-07-16 03:45 UTC, seeflood commented on demo/file/stressmem.go
> +	//分片上传，片最小为100kb
同上

2021-07-16 03:45 UTC, seeflood commented on demo/file/stressmem.go
> +		// 控制条件,根据实际调整
同上

2021-07-16 03:45 UTC, seeflood commented on components/file/file.go
> +	CompletePut(int64) error
这个CompletePut是啥，可以补充下注释或者文档哈
因为组件接口定义出来的目标是让其他贡献者不需要来口头询问、直接就能开发组件，看不懂的话会劝退开发者

2021-07-16 07:34 UTC, wenxuwan commented on demo/file/stressmem.go
> +		// 控制条件,根据实际调整
done

2021-07-16 07:34 UTC, wenxuwan commented on demo/file/client.go
> +		// 控制条件,根据实际调整
done

2021-07-16 07:34 UTC, wenxuwan commented on demo/file/client.go
> +	//分片上传，片最小为100kb
done

2021-07-16 07:34 UTC, wenxuwan commented on demo/file/stressmem.go
> +	//分片上传，片最小为100kb
done

2021-07-16 07:34 UTC, wenxuwan commented on components/file/file.go
> +	CompletePut(int64) error
已加

2021-09-22 07:23 UTC, zhenjunMa approved these changes

2021-09-22 07:25 UTC, merged