sequencer redis
mosn/layotto pull request #152
Opened 2021-07-24 06:26 UTC by ZLBer

**What this PR does**:
add  sequencer redis
**Which issue(s) this PR fixes**:

Fixes #150 

**Special notes for your reviewer**:
@seeflood 
**Does this PR introduce a user-facing change?**:

```release-note

```

2021-07-26 13:55 UTC, seeflood commented
ZLBer同学太强了 👍 👍 👍

2021-07-26 15:05 UTC, seeflood requested changes

2021-07-26 15:10 UTC, seeflood commented
另外看代码的时候突然想到个问题，记录下：
比如用户的state、lock、sequencer API都用redis，那么key可能有冲突
这个问题可以在runtime层做下改动，比如自动给key带上前缀`state||appid||key1` ,`sequencer||appid||key1`这样。
组件不用管这个事情，我提个pr改下runtime吧

2021-07-26 16:04 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
segment这个是直接把号段返回给用户吗 ？fromt,to要是不连续怎么办 ? 哦..是自增id..那感觉可以form,to 闭区间返回

2021-07-26 16:05 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
或者加个字段让用户决定是不是初始化？

2021-07-26 16:08 UTC, ZLBer commented
> 另外看代码的时候突然想到个问题，记录下：
> 比如用户的state、lock、sequencer API都用redis，那么key可能有冲突
> 这个问题可以在runtime层做下改动，比如自动给key带上前缀`lock||appid||key1` ,`sequencer||appid||key1`这样。
> 组件不用管这个事情，我提个pr改下runtime吧

这个很有必要

2021-07-27 02:57 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
这里是直接把号段返回给runtime层，runtime层有个缓存、每次从缓存里取号给用户~
只不过runtime层的这个方法还没实现，作为社区任务发出来了，如果没人领的话过两天我写下~

2021-07-27 03:09 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
> 或者加个字段让用户决定是不是初始化？

这块我也和@zhenjunMa 讨论了下，感觉如果加个配置项，对用户来说就更复杂了一些；想对用户来说用起来更简单点，要不redis就根据biggerThan自动set值吧？

这样不同组件在init的时候，能自动初始化的就自动初始化，不能的就启动报错，如何

2021-07-27 06:20 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
那runtime层直接被kill了怎么办 ？这些号id就直接被弃用了吗

2021-07-27 06:21 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
可以哈

2021-07-27 06:44 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
是的，丢就丢了，丢个几百几千的问题不大

2021-07-27 06:47 UTC, seeflood commented
> > 另外看代码的时候突然想到个问题，记录下：
> > 比如用户的state、lock、sequencer API都用redis，那么key可能有冲突
> > 这个问题可以在runtime层做下改动，比如自动给key带上前缀`lock||appid||key1` ,`sequencer||appid||key1`这样。
> > 组件不用管这个事情，我提个pr改下runtime吧
> 
> 这个很有必要

恩恩我记了个issue给自己 稍后会改掉 #154

2021-07-27 10:10 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
ok, fine

2021-07-28 08:25 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
@seeflood  这里并发失败要怎么处理呢？重试策略还是报错呢

2021-07-28 09:46 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
@seeflood 还有就是key不存在,是报错还是初始化呢

2021-07-28 10:08 UTC, ZLBer commented
@seeflood   新的commit修改了上面的问题 并修改了segmentResponse

2021-07-28 14:41 UTC, ZLBer commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
@seeflood  有个问题呀  像SnowFlake这种不是一个个递增的id  from,to这种方案就不合适了吧

2021-07-28 14:51 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
key不存在可以帮忙创建初始化；
关于并发，这里的初始化语句就不是compareAndSet了，而是写一个lua，实现以下逻辑：
```
if key1的value  < biggerThan then
  set(key1,biggerThan)

```
（估计这种逻辑应该没法用redis自带的api写吧？应该是用Lua)
我记得lua是默认单线程执行的，就不存并发问题啦

2021-07-29 09:43 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +func (s *StandaloneRedisSequencer) GetSegment(req *sequencer.GetSegmentRequest) (support bool, result *sequencer.GetSegmentResponse, err error) {
不好意思刚看到这个回复……GetSegment会返回一个support bool字段，snowflake这种不支持号段缓存、返回false即可

2021-07-29 11:26 UTC, seeflood commented on components/sequencer/redis/standalone_redis_sequencer.go
> +	for k, bt := range s.metadata.biggerThan {
哦补充下，这个lua还得判断key1对应的value是不是数字，不是数字的话需要在init阶段报错

2021-07-30 09:08 UTC, ZLBer commented
@seeflood  new commit  for above  problem

2021-08-04 06:42 UTC, seeflood commented
看着没问题了，就是之前我提了个pr，把组件的一些模板代码（比如创建redis和etcd客户端的代码）抽出来成一个公用的工具类了
这个我在你的分支上改下代码吧

2021-08-04 06:48 UTC, seeflood commented
另外就是需要在组件配置里声明，redis组件可能出现id冲突，为了避免冲突需要使用单机redis、把持久化配置都调到最强

2021-08-04 07:16 UTC, seeflood commented
@ZLBer 我给你的分支提交了修改，辛苦你review下哈~包括：
1. sidebar里加上了文档
2. 使用了公用的utils方法，删掉冗余代码
3. 组件配置里加入声明，redis组件可能出现id冲突，为了避免冲突需要使用单机redis、把持久化配置都调到最强

2021-08-05 03:36 UTC, ZLBer commented
@seeflood  LGTM

2021-08-05 03:37 UTC, merged