sequencer zookeeper
mosn/layotto pull request #156
Opened 2021-07-28 12:46 UTC by ZLBer

**What this PR does**:
add  sequencer zookeeper
**Which issue(s) this PR fixes**:

Fixes #150  

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-07-28 12:47 UTC, ZLBer commented
有个问题，zk的version只支持到int32

2021-08-04 12:02 UTC, seeflood reviewed
> 有个问题，zk的version只支持到int32

我刚才请教了同事，他说很多公司现在在把id从32位升级到64位，他之前在美团某业务就遇到了id快溢出的问题……
所以我们就不考虑把API改成int32了
那么解决这个问题的方案：
a. zk在组件文档上写个warning:本组件最大2的31次方，超过会溢出
b. 想办法用其他api实现这个功能（我没找到，需要再查查文档……

2021-08-04 12:09 UTC, seeflood requested changes

2021-08-04 12:09 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	return &sequencer.GetNextIdResponse{
如果确定只支持int32 那这里就得判断version是不是溢出变成负数了，溢出就报错

2021-08-04 12:09 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +func parseRedisMetadata(config sequencer.Configuration) (metadata, error) {
另外这些模板代码可以挪到utils里~ 这样zookeeper的sequencer组件和lock组件都调utils做配置解析、创建连接等操作，减少代码重复
参考components/pkg/utils/etcd.go  和components/pkg/utils/redis.go

2021-08-05 04:21 UTC, ZLBer commented
> 我刚才请教了同事，他说很多公司现在在把id从32位升级到64位，他之前在美团某业务就遇到了id快溢出的问题……
> 所以我们就不考虑把API改成int32了
> 那么解决这个问题的方案：
> a. zk在组件文档上写个warning:本组件最大2的31次方，超过会溢出
> b. 想办法用其他api实现这个功能
> 
> 关于b方案，我查了一下文档，java的curator是通过value值做的自增id，具体来说，先乐观锁执行get--add--set，如果set发现冲突再重试/升级成悲观锁。见http://curator.apache.org/curator-recipes/distributed-atomic-long.html
> 
> 考虑到curator没有go版本，自己写的话太复杂了，我们先选择a方案吧，zk就只支持到int32，在文档里写上warning

@seeflood  get !  我晚点改一下

2021-08-06 16:43 UTC, ZLBer commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	return &sequencer.GetNextIdResponse{
这里溢出的话 zk会把version重置成0 , 我可以根据0来判断溢出，但是下次调用就会返回正常的version ，这该怎么处理？

2021-08-06 16:46 UTC, ZLBer commented
@seeflood   a commit for above conversation

2021-08-06 17:02 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	return &sequencer.GetNextIdResponse{
哇这个问题好难搞
简单的方案是溢出之后就不可用：
a. 内存里留个flag，溢出后zk组件不可用；
b. 内存里每个key对应一个flag，溢出后该key就不能再生成id了

但是其实重启了（或者被k8s自动kill重新部署了）这个flag也没啥用；
以及生产用户如果遇到问题，就是灾难（他必须重启所有sidecar才能恢复可用）

但是如果搞成溢出后依然可用，又有可能id重复，出现意想不到的问题

要不就设计成溢出后该key不可用，在文档里也注明一下？

2021-08-06 17:20 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	return &sequencer.GetNextIdResponse{
晚上喝了酒糊涂了……这个问题解决不了，就打个error日志吧，在文档里声明下溢出了也不会做啥处理

2021-08-10 07:46 UTC, seeflood requested changes

2021-08-10 07:46 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	if stat.Version == 0 {
这里有个问题，正数溢出后应该是负数，而不是0
当然我不清楚zk会不会做一些把负数变0的事情
要不这里判断<=0就报错？

2021-08-10 07:46 UTC, seeflood commented
另外我改了一下你的分支里的文档~所以你记得拉下代码再修改哈

2021-08-10 07:49 UTC, seeflood commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	if stat.Version <= 0 {
这里判断==0的haul有个问题，正数溢出后应该是负数，而不是0
当然我不清楚zk会不会做一些把负数version变0的事情
我直接帮你改成<=0了哈

2021-08-12 08:59 UTC, ZLBer commented on components/sequencer/zookeeper/zookeeper_sequencer.go
> +	if stat.Version <= 0 {
fine

2021-08-12 08:59 UTC, ZLBer commented
@seeflood  LGTM

2021-08-12 09:16 UTC, merged