feat: load multi wasm plugins
mosn/layotto pull request #182
Opened 2021-08-13 14:23 UTC by zu1k

**What this PR does**:

Let layotto support loading multi wasm plugins

**Which issue(s) this PR fixes**:

Fixes #176 

**Special notes for your reviewer**:

Idea validation, not completed, encountered major obstacles

**Does this PR introduce a user-facing change?**:

```release-note
config stream_filters changed
```

2021-08-17 22:05 UTC, zhenjunMa requested changes

2021-08-17 22:14 UTC, zu1k commented on demo/wasm/code/golang/wasm.go
> +	id := ID
第一行是为了在编译期检查id是否为空，下一行是因为const类型没办法取指针

2021-08-17 22:27 UTC, zu1k commented on demo/wasm/config.json
> +                  "name": "id_1",
确实，我也好奇原本代码为啥没有不加个name，等看看如果没必要可以直接让config的key作为相应item的name

2021-08-18 00:23 UTC, zu1k commented on demo/wasm/config.json
> +                  "name": "id_1",
这个struct是在mosn/config/v2里面定义的，layotto改不了

2021-08-18 01:30 UTC, zu1k commented on pkg/wasm/filter.go
> +		id, err := exports.ProxyGetID()
不太行，获取ID需要`GetFuncCallData()`，这个函数是Filter里LayottoHandler实现的，需要在NewFilter的时候注入Imports的具体实现，所以GetID这个行为只能在NewFilter的时候进行。。。
我刚刚尝试将这个过程提前到Factory阶段，发现了这个依赖问题。

2021-08-18 01:33 UTC, zu1k commented on pkg/wasm/filter.go
> +		pluginABI.SetABIImports(filter)
这里的GetABI不会对`Imports`设置吧，`Imports`的实现在LayottoHandler，需要在这个阶段注入Imports供wasm调用

2021-08-18 01:39 UTC, zu1k commented on pkg/wasm/filter.go
> +		instance := plugin.GetInstance()
看起来要在`Filter.OnReceive()`的时候，判断完`id`后再`GetInstance`取相应plugin的一个实例

2021-08-18 01:43 UTC, zu1k commented on pkg/wasm/filter.go
> +		id, err := exports.ProxyGetID()
看样子获取最终的`Instance`需要在判断完用户指定的`id`之后，也就是说给`Instance`对应的`WasmModule`注入`Imports`也要延后到`OnReceive`的时候进行

2021-08-19 03:03 UTC, zhenjunMa commented on pkg/wasm/filter.go
> +		pluginABI.SetABIImports(filter)
我看你最新的提交把`abiImplFactory `里面设置import的代码删了，那这里就不冲突了

2021-08-19 03:07 UTC, zhenjunMa commented on demo/wasm/config.json
> +                  "name": "id_1",
你说的在mosn里应该是`v2.WasmVmConfig`吧，如果要加name的话，应该加在你写的`filterConfigItem`里

2021-08-19 03:11 UTC, zhenjunMa commented on pkg/wasm/filter.go
> +		id, err := exports.ProxyGetID()
有点tricky，我本来看你在`abiImplFactory`里面设置了import，这种情况下应该不会有这个依赖问题，但如果你把设置import的时机改回去了，应该确实需要调整一下🍺

2021-08-19 03:22 UTC, zhenjunMa commented on pkg/wasm/filter.go
> +		id, err := exports.ProxyGetID()
我看了下代码，目前的死锁应该是factory阶段设置的import是factory，filter阶段设置的import是filter，而你的逻辑写在filter里面，这就调不了了，有没有可能尝试一下两个阶段使用一个import？

2021-08-19 08:23 UTC, zu1k commented on demo/wasm/config.json
> +                  "name": "id_1",
这个暂时用不到，后面再单独提PR处理吧

2021-08-19 09:17 UTC, zu1k commented
在wasm实例数大于1的时候，遇到了这样的错误：

```
call foreign func failed: unknown status code: 12
```

没找到这个我看Status枚举最多到10，这个12是什么错误啊

2021-08-20 02:49 UTC, zhenjunMa requested changes

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/factory.go
> +			log.DefaultLogger.Errorf("[proxywasm][factory] createProxyWasmFilterFactory fail to get wasm id, PluginName: %v, err: %v",
%v -> %s

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/filter.go
>  	return f.factory.GetVmConfig()
这里应该返回`f.pluginUsed.plugin.GetVmConfig()`吧？下面的plugConfig也类似

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/factory.go
>  			vmConfigSize = vmConfigBytes.Len()
这里的`GetVmConfig `跟下面的`GetPluginConfig `返回都是nil，内容应该需要从plugin中获取，只不过还得加上转换成byte[]的逻辑，你现在把之前在factory里面的`vmConfigBytes`跟`pluginConfigBytes`删没了

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/factory.go
> +		pluginABI := abi.GetABI(instance, AbiV2)
从这里开始，不过上面获取Instance的逻辑只是为了取出ID，这部分逻辑可以挪到`OnPluginStart`中，可以减少很多代码

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/factory.go
> +		factory.router.RegisterRoute(id, wasmPlugin)
目前这个构建路由表的逻辑还是以plugin为粒度的，由于一个plugin下面可能会对应多个instance，流量会打在一个instance上，所以按理来说路由表应该是以instance粒度，虽然目前资源的划分是plugin为粒度的，不过我们暂时认为如果相同资源下面可以启动多个instance，那处理能力也应该是几倍

2021-08-20 02:49 UTC, zhenjunMa commented on pkg/wasm/filter.go
>  		f.instance.Lock(f.abi)
跑代码的时候发现个问题，如果请求传入的目标id找不到，那么instance就是nil，然后调用destroy的时候这里就空指针了

2021-08-20 02:50 UTC, zhenjunMa commented
整体思路完全正确👍，部分细节可以再讨论下

2021-08-20 03:14 UTC, zu1k commented on pkg/wasm/factory.go
> +		factory.router.RegisterRoute(id, wasmPlugin)
实际OnReceive 的时候会GetInstance，我看那里目前实现的是轮询，不会落到一个instance上吧

2021-08-20 03:44 UTC, zhenjunMa commented on pkg/wasm/factory.go
> +		factory.router.RegisterRoute(id, wasmPlugin)
我理解你现在的逻辑应该是这样的，假设配置如下：
```
"id_1_1": {
  "name": "id_1",
  "instance_num": 1,
  "vm_config": {
    "engine": "wasmer",
    "path": "demo/wasm/code/golang/wasm_1_1.wasm"
  }
},
"id_1_2": {
  "name": "id_1",
  "instance_num": 2,
  "vm_config": {
    "engine": "wasmer",
    "path": "demo/wasm/code/golang/wasm_1_2.wasm"
  }
```
最终路由表会是 id_1对应两个plugin，而这两个plugin会均分id_1下面的所有流量，当然针对plugin2来说，它的两个instance是各自处理25%的流量，但如果从instance的角度来说，对于id_1的所有流量，plugin1应该承担33%   plugin2应该承担66%   因为它们的intance比例是1:2

2021-08-20 04:06 UTC, zu1k commented on pkg/wasm/factory.go
> +		factory.router.RegisterRoute(id, wasmPlugin)
明白了

2021-08-20 05:26 UTC, zu1k commented
一开始想改成加权轮训，不过发现把注册路由放到OnPluginStart里其实会每一个instance都注册一次，实际上已经等于是加权了，所以又改回随机了

2021-08-20 05:28 UTC, zu1k commented
也就是说getID这个行为，每一个wasm都会运行instanceNum次，我觉得还是放在原来的位置好

2021-08-20 07:15 UTC, zhenjunMa commented
是的，放在`createProxyWasmFilterFactory`会感觉代码有冗余，放在`OnPluginStart`又会按照instance维度反复获取ID，好在这种方式会把请求自动打散在Instance粒度，  两种写法都有瑕疵，感觉可能我们在wasm生命周期管理这块还有优化的空间。

2021-08-20 07:16 UTC, zhenjunMa approved these changes
非常感谢贡献如此重要的feature🍺

2021-08-20 08:12 UTC, merged