docs: move feature list into table
mosn/layotto pull request #273
Opened 2021-10-21 04:02 UTC by zhenjunMa

**What this PR does**:

Modify the description of various APIs in READ.ME into a table format to improve the reading experience.

2021-11-10 06:14 UTC, seeflood requested changes
I just modified the description in your branch.
Please add File API and binding API related docs

2021-11-10 06:17 UTC, seeflood requested changes
Also,please add docs for using wasm for sidecar extension (not as faas)

2021-11-11 05:41 UTC, zhenjunMa commented
@seeflood  fixed

2021-11-11 06:08 UTC, seeflood requested changes

2021-11-11 06:08 UTC, seeflood commented on docs/en/start/wasm/start.md
> +## WASM on Layotto
please add this doc into sidebar

2021-11-11 06:08 UTC, seeflood commented on docs/zh/start/wasm/start.md
> +## WASM概述
please add this doc into sidebar

2021-11-11 06:08 UTC, seeflood commented on docs/zh/README.md
> +### 通过WebAssembly (WASM)做扩展、写FaaS
这两段的标题都是 “通过WebAssembly (WASM)做扩展、写FaaS”
需要区分下

2021-11-11 07:08 UTC, seeflood approved these changes
LGTM

2021-11-11 07:12 UTC, merged