feature: support dapr state api
mosn/layotto pull request #377
Opened 2021-12-28 13:19 UTC by zach030

**What this PR does**:

feature: 
1. support dapr state api
2. integrate dapr API with `default_api`
3. add some converter codes
4. implement `QueryStateAlpha1` and add some missing error-msg consts

**Which issue(s) this PR fixes**:

Fixes #361 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-12-29 01:06 UTC, seeflood commented
Thanks for your contribution !
Please check and fix the CI failure.
@wenxuwan Could u help review this PR?

2021-12-29 02:16 UTC, wenxuwan commented
> Thanks for your contribution ! Please check and fix the CI failure. @wenxuwan Could u help review this PR?

ok

2021-12-29 14:22 UTC, wenxuwan commented
@zach030 please fix the failed ci first

2021-12-29 15:17 UTC, zach030 commented
> @zach030 please fix the failed ci first

Yes. But I don't know the reason of CI failure now 🥲

2021-12-30 02:09 UTC, wenxuwan commented
> > @zach030 please fix the failed ci first
> 
> Yes. But I don't know the reason of CI failure now 🥲

should be cause by cel-go version, you can check cel-go version in the go.sum

2021-12-30 10:17 UTC, zach030 commented
> > > @zach030 please fix the failed ci first
> > 
> > 
> > Yes. But I don't know the reason of CI failure now 🥲
> 
> should be cause by cel-go version, you can check cel-go version in the go.sum

我查了一下，我的这次修改引入了对dapr的依赖：`github.com/dapr/dapr v1.5.1`
dapr依赖的cel-go的版本是`github.com/google/cel-go v0.7.3` ，而mosn依赖的版本是`github.com/google/cel-go v0.5.1`

然后我对比了一下v0.7.3和v0.5.1 https://github.com/google/cel-go/compare/v0.5.1...v0.7.3
`common/types/duration.go` 两个版本里有比较大的差异
![image](https://user-images.githubusercontent.com/51114270/147742433-84e65992-6aea-4606-b21d-8d5f60886236.png)

2021-12-31 02:57 UTC, wenxuwan commented
> > > > @zach030 please fix the failed ci first
> > > 
> > > 
> > > Yes. But I don't know the reason of CI failure now 🥲
> > 
> > 
> > should be cause by cel-go version, you can check cel-go version in the go.sum
> 
> 我查了一下，我的这次修改引入了对dapr的依赖：`github.com/dapr/dapr v1.5.1` dapr依赖的cel-go的版本是`github.com/google/cel-go v0.7.3` ，而mosn依赖的版本是`github.com/google/cel-go v0.5.1`
> 
> 然后我对比了一下v0.7.3和v0.5.1 [google/cel-go@v0.5.1...v0.7.3](https://github.com/google/cel-go/compare/v0.5.1...v0.7.3) `common/types/duration.go` 两个版本里有比较大的差异 ![image](https://user-images.githubusercontent.com/51114270/147742433-84e65992-6aea-4606-b21d-8d5f60886236.png)

替换成0.5.1看dapr那边会不会报错

2022-01-04 02:32 UTC, zach030 commented
@wenxuwan already fixed ci failure

2022-01-04 02:41 UTC, wenxuwan commented
> @wenxuwan already fixed ci failure

ok， i will review asap

2022-01-07 08:46 UTC, MoonShining commented on pkg/grpc/default_api/api_state.go
> +	ret := make([]*dapr_v1pb.TransactionalStateOperation, 0)
init with len(ops)

2022-01-07 15:46 UTC, zach030 commented on pkg/grpc/default_api/api_state.go
> +	ret := make([]*dapr_v1pb.TransactionalStateOperation, 0)
> init with len(ops)
done

2022-01-10 11:44 UTC, wenxuwan submitted a review, later dismissed
LGTM

2022-01-11 09:21 UTC, seeflood requested changes

2022-01-11 09:21 UTC, seeflood commented on go.mod
> +	github.com/dapr/dapr v1.5.1
Hi, we don't really need to import 'dapr/dapr',which might cause dependency conflicts

2022-01-11 09:53 UTC, seeflood requested changes

2022-01-11 09:53 UTC, seeflood commented on pkg/grpc/dapr/dapr_api_state.go
> +	encrypted := encryption.EncryptedStateStore(request.StoreName)
hi, 加密应该是dapr的新功能，需要整体上做支持，包括：
- runtime初始化的时候，注册”哪些state store需要加密“
- 要加密的话每个api都应该支持加密，不太适合只针对这一个API加

我们可以后续迭代专门起个pr做加密相关功能，等 #343 合并进去之后；这次加密相关的代码可以先去掉哈~

2022-01-11 11:05 UTC, zach030 commented
@seeflood 移除了加密部分的代码，还有对 `github.com/dapr/dapr v1.5.1`的依赖，目前看来没有版本冲突的问题了

2022-01-13 07:43 UTC, seeflood commented
FYI, I removed some unused code,e.g. `pkg/converter/state.go`

2022-01-13 09:07 UTC, seeflood approved these changes
lgtm

2022-01-13 09:17 UTC, wenxuwan approved these changes
LGTM

2022-01-13 09:17 UTC, merged