add metric config for layotto
mosn/layotto pull request #380
Opened 2022-01-14 03:03 UTC by wenxuwan

**What this PR does**:

add metric config for layotto #379 

user can use curl --location --request GET 'http://127.0.0.1:34903/metrics' to get metric of mosn, and result is:

![image](https://user-images.githubusercontent.com/11661906/149444402-a83952af-f041-4895-a417-81f4d79bde85.png)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-01-14 13:08 UTC, seeflood commented
Great ! Could u please add a simple document for it ?

2022-01-25 07:55 UTC, zhenjunMa requested changes

2022-01-25 07:55 UTC, zhenjunMa commented on docs/zh/start/trace/trace.md
> +layotto的metric复用的mosn的metric，对接prometheus，[runtime_config.json](../../../../configs/runtime_config.json)中提供了metric配置的示例，按照上述步骤启动layotto后，可以通过一下指令读取metric信息：
"一下" -> "以下"

2022-01-25 07:56 UTC, zhenjunMa commented on docs/en/start/trace/trace.md
> +###Metric
这里少了一个空格，格式有问题

2022-01-25 07:58 UTC, wenxuwan commented on docs/zh/start/trace/trace.md
> +layotto的metric复用的mosn的metric，对接prometheus，[runtime_config.json](../../../../configs/runtime_config.json)中提供了metric配置的示例，按照上述步骤启动layotto后，可以通过一下指令读取metric信息：
done

2022-01-25 07:58 UTC, wenxuwan commented on docs/en/start/trace/trace.md
> +###Metric
done

2022-01-25 08:04 UTC, zhenjunMa submitted a review, later dismissed

2022-01-25 08:08 UTC, seeflood requested changes

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
> +##Observability (trace, metric)
这里少了一个空格，格式有问题(不知道为啥我没法直接编辑

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  You can implement your own Generator, you can refer to the implementation of [OpenGenerator](../../../../diagnostics/genetator.go) in the code.
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  Refer to the implementation of [StdoutExporter](../../../../diagnostics/exporter_iml/stdout.go), which will print trace information to standard output.
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  You can refer to the implementation of [OpenGenerator](../../../../diagnostics/genetator.go) in the code
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  On the Component side, you can insert component information through [SetExtraComponentInfo](../../../../components/trace/utils.go),
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  For example, the following operations are performed on the interface [Hello](../../../../components/hello/helloworld/helloworld.go):
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
>  Tracing in Layotto is mainly to record grpc calls, which relies on two interceptors added in grpc： [UnaryInterceptorFilter](../../../../diagnostics/grpc_tracing.go)、 [StreamInterceptorFilter](../../.
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/en/start/trace/trace.md
> +Layotto's metric reuses mosn's metric, and connects to prometheus. An example of metric configuration is provided in [runtime_config.json](../../../../configs/runtime_config.json), follow the above s
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  可以实现自己的Generator，可以参考代码中的[OpenGenerator](../../../../diagnostics/genetator.go)的实现。
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  参照[StdoutExporter](../../../../diagnostics/exporter_iml/stdout.go)的实现,该实现将trace的信息打印到标准输出。
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  可以参考代码中的[OpenGenerator](../../../../diagnostics/genetator.go)的实现
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  比如在接口[Hello](../../../../components/hello/helloworld/helloworld.go)执行了以下操作：
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  在Component侧可以通过[SetExtraComponentInfo](../../../../components/trace/utils.go)塞入component的信息，
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
>  Layotto中的tracing主要是对grpc调用进行记录，依赖于在grpc里添加的两个拦截器： [UnaryInterceptorFilter](../../../../diagnostics/grpc_tracing.go)、 [StreamInterceptorFilter](../../../../diagnostics/grpc_tracing.go)
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 08:08 UTC, seeflood commented on docs/zh/start/trace/trace.md
> +layotto的metric复用的mosn的metric，对接prometheus，[runtime_config.json](../../../../configs/runtime_config.json)中提供了metric配置的示例，按照上述步骤启动layotto后，可以通过以下指令读取metric信息：
点击跳转的链接需要用绝对路径，不然在"https://mosn.io/layotto/" 点了这个链接会打不开。类似这样：
![image](https://user-images.githubusercontent.com/26001097/150936106-20b4d876-7068-4034-8962-672e43831a61.png)
注：图片可以用相对路径
详细解释可以参考[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc?id=%e7%bb%8f%e5%b8%b8%e9%81%87%e5%88%b0%e7%9a%84%e5%9d%91%ef%bc%9a%e6%96%87%e6%a1%a3%e5%86%85%e7%9a%84%e8%b6%85%e9%93%be%e6%8e%a5)

2022-01-25 09:17 UTC, wenxuwan commented on docs/en/start/trace/trace.md
> +##Observability (trace, metric)
done

2022-01-25 09:25 UTC, wenxuwan commented on docs/en/start/trace/trace.md
>  You can implement your own Generator, you can refer to the implementation of [OpenGenerator](../../../../diagnostics/genetator.go) in the code.
done

2022-01-25 11:59 UTC, seeflood approved these changes
lgtm

2022-01-26 02:40 UTC, zhenjunMa approved these changes

2022-01-26 02:41 UTC, merged