feat: add skywalking trace
mosn/layotto pull request #404
Opened 2022-03-03 11:13 UTC by stulzq

**What this PR does**:
add skywalking tracer
**Which issue(s) this PR fixes**:

#310 
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-03-07 03:20 UTC, wenxuwan commented on diagnostics/grpc_tracing.go
> -	err := handler(srv, wrapped)
这个地方改成handler(ctx, ss)，stream没法将ctx的header传递下去吧

2022-03-10 07:49 UTC, wenxuwan commented on diagnostics/grpc_tracing.go
> +	err := handler(ctx, wrapped)
第一个参数改成ctx的原因是什么，上下文应该在第二个参数里面的ctx中

2022-03-10 07:55 UTC, stulzq commented on diagnostics/grpc_tracing.go
> +	err := handler(ctx, wrapped)
我的锅 c/v 的时候没注意

2022-03-10 11:27 UTC, wenxuwan submitted a review, later dismissed
LGTM

2022-03-11 14:40 UTC, seeflood commented
Thanks !
I just changed the `config_stores` in config.json  to `config_store`

2022-03-18 05:55 UTC, zhenjunMa submitted a review, later dismissed

2022-03-20 08:50 UTC, seeflood commented
Got an error when running the demo:
![image](https://user-images.githubusercontent.com/26001097/159154988-06e6d124-534b-45a6-909e-ec3cb9e8098b.png)
It seems that the main.go forgot to import grpcmetric package. I will help fix it

2022-03-20 09:34 UTC, seeflood commented
fixed. 
Besides, I modified the document and added it to the sidebar

2022-03-20 11:36 UTC, seeflood commented on diagnostics/grpc_tracing.go
> -	span.SetTag(ltrace.LAYOTTO_REQUEST_RESULT, "0")
Why delete them?

2022-03-20 13:15 UTC, seeflood requested changes

2022-03-20 13:15 UTC, seeflood commented on diagnostics/skywalking/grpc_tracer.go
> +	*ltrace.Span
So `grpcSkySpan.SetTag` will actually invoke `*ltrace.Span.SetTag` .
But the tags will be ignored when `grpcSkySpan.End()` . So finally we lost the tags.
Am I right? I think these tags should be sent to SkyWalking too.

2022-03-20 14:24 UTC, stulzq commented on diagnostics/grpc_tracing.go
> -	span.SetTag(ltrace.LAYOTTO_REQUEST_RESULT, "0")
移动到了这边 diagnostics/tracing.go

2022-03-20 14:24 UTC, stulzq commented on diagnostics/grpc_tracing.go
> -	span.SetTag(ltrace.LAYOTTO_REQUEST_RESULT, "0")
https://github.com/mosn/layotto/pull/404/files#diff-360719837a63f9a6d3b8c94a5bc6f97daa5901a20bd04a620e2298aced617032R51

2022-03-20 14:26 UTC, stulzq commented on diagnostics/skywalking/grpc_tracer.go
> +	*ltrace.Span
sky 不支持自定义 tag , https://github.com/mosn/mosn/blob/master/pkg/trace/skywalking/span.go#L53

2022-03-20 15:33 UTC, seeflood commented on diagnostics/skywalking/grpc_tracer.go
> +	*ltrace.Span
好吧，有点奇怪……那先记个TODO 以后再优化吧

2022-03-20 15:41 UTC, seeflood commented on diagnostics/grpc_tracing.go
> -	span.SetTag(ltrace.LAYOTTO_REQUEST_RESULT, "0")
恩恩看到了，主要是感觉，更适合把SetTag放在这里，因为：
1. `UnaryInterceptorFilter`是放这的，如果`StreamInterceptorFilter`不放这的话，不一致（强迫症看着难受 
![image](https://user-images.githubusercontent.com/26001097/159170235-43fdef24-64d7-43e1-b7cc-ca1787a6b557.png)

2. 放这的好处是不用每个span都去写这两行了（虽然现在skywalking的span 没法setTag）
3. 上下一致，下面有个set "1", 如果把上面的 set "0"删了 看着有点不一致
![image](https://user-images.githubusercontent.com/26001097/159170419-bfee180b-d768-49fd-a670-f764a8498e7c.png)

2022-03-21 03:01 UTC, stulzq commented on diagnostics/grpc_tracing.go
> -	span.SetTag(ltrace.LAYOTTO_REQUEST_RESULT, "0")
我改下，当时移动的初衷是不是每个span
都需要设置这个

2022-03-22 01:47 UTC, seeflood requested changes

2022-03-22 01:47 UTC, seeflood commented on docs/zh/start/trace/skywalking.md
> +# Skywalking trace 接入
Could u also add this great document into our README-zh.md?
https://mosn.io/layotto/#/zh/README

I think we can add a new table for Observability
![image](https://user-images.githubusercontent.com/26001097/159390908-33373701-072a-45f1-b23e-715ee0c54707.png)

2022-03-25 10:06 UTC, seeflood approved these changes
lgtm. Thanks for your great contribution!

2022-03-25 10:43 UTC, zhenjunMa approved these changes

2022-03-25 11:09 UTC, merged