doc: translate 'explanation-for-github-workflow' into chinese
mosn/layotto pull request #474
Opened 2022-04-13 13:52 UTC by jieeny

2022-04-13 15:34 UTC, seeflood requested changes

2022-04-13 15:34 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +如果一个issue或PR在过去30天内没有最近的活动，它将自动标记为陈旧的。它将关闭在未来7天，除非它是被标记的(pinned，security，good first issue或help wanted)或有其他活动发生。
它将关闭在未来7天  =》 它将在7天后关闭

2022-04-13 15:34 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +#### TODO: 在修改proto文件时自动生成新的API引用
API引用  =》 API 文档

2022-04-13 15:34 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +#### TODO: 综合测试
综合测试 =》 集成测试

2022-04-13 15:34 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
>  In Layotto directory:
”In Layotto directory“
这句话可以删了哈

2022-04-13 15:34 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +我们可以使用 go lint 和 参考MOSN的配置
我们可以使用 go lint, 参考MOSN的配置

2022-04-20 01:45 UTC, jieeny commented
Hi, I have a question, ”ubuntu-latest - Go 1.14.13 Expected — Waiting for status to be reported“ , how can I resolve this question?

2022-04-20 02:28 UTC, seeflood commented
@jieeny It starts running now.
That's a mechanism of github. A pull request from a first-time contributor can not automatically trigger the CI pipeline untile a maintainer manually starts it.
A little bit annoying :)

2022-04-20 02:44 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +如果一个issue或PR在过去30天内没有最近的活动，它将自动标记为陈旧的。它将关闭在未来7天，除非它是被标记的(pinned，security，good first issue或help wanted)或有其他活动发生。
@jieeny hi, it seems that you didn't reslove these review issues?

2022-04-20 02:48 UTC, seeflood requested changes

2022-04-20 02:48 UTC, seeflood commented on docs/zh/development/explanation-for-github-workflow.md
> +注意：Layotto的github工作流的配置文档在[这里](https://github.com/mosn/layotto/tree/main/.github/workflows)
配置文档 => 配置文件

2022-04-29 06:13 UTC, seeflood commented
Thanks for your help. I modified your branch and fixed the review issues.

2022-04-29 06:13 UTC, seeflood approved these changes
lgtm

2022-04-29 06:15 UTC, wenxuwan approved these changes

2022-04-29 06:17 UTC, merged