feat: upgrade assemblyscript faas demo(#256)
mosn/layotto pull request #486
Opened 2022-04-18 05:57 UTC by nanjingboy

**What this PR does**:

Upgrade the wasm demo developed by AssemblyScript(#256)

**Special notes for your reviewer**:

The Node.js version should >=16.14.0

2022-04-18 05:58 UTC, nanjingboy commented
@seeflood

2022-04-19 11:27 UTC, zu1k requested changes

2022-04-19 14:42 UTC, nanjingboy commented on demo/faas/code/assemblyscript/assembly/client.ts
> +      set_http_response_body(`There are ${String.UTF8.decode(invokeService("id_2", "", name))} inventories for ${name}.\n`);
updated

2022-04-20 05:58 UTC, nobodyiam approved these changes
LGTM

2022-04-20 14:42 UTC, zu1k commented
I'm not familiar with assemblyscript, but LGTM.

2022-04-20 14:43 UTC, zu1k approved these changes

2022-04-21 02:28 UTC, seeflood commented
Thanks for your contribution! We can merge this PR and #475 after v0.4 released

2022-04-22 10:09 UTC, seeflood approved these changes
lgtm

2022-04-22 10:09 UTC, zhenjunMa approved these changes

2022-04-22 11:13 UTC, merged