feature: Decoupled type
mosn/layotto pull request #549
Opened 2022-05-08 14:05 UTC by akkw

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-05-10 03:07 UTC, seeflood commented
@zhenjunMa Please help review this PR

2022-05-11 14:36 UTC, akkw commented
> 这个改动要考虑兼容问题？如果用户升级了Layotto，但配置文件没变，那是不是加载就出问题，可以做成如果没配置type字段就用原先的作为type名字

这样子我感觉对于存量用户是不是配置文件会比较混乱啊，统一性没有标准。
其次，这个改动其实对于配置文件来说改动不是很大甚至我们可以实现一个小工具去帮助用户升级配置文件，这些我觉得难度都不是很大

2022-05-12 02:02 UTC, wenxuwan commented
> > 这个改动要考虑兼容问题？如果用户升级了Layotto，但配置文件没变，那是不是加载就出问题，可以做成如果没配置type字段就用原先的作为type名字
> 
> 这样子我感觉对于存量用户是不是配置文件会比较混乱啊，统一性没有标准。 其次，这个改动其实对于配置文件来说改动不是很大甚至我们可以实现一个小工具去帮助用户升级配置文件，这些我觉得难度都不是很大

这个问题不能用升级难不难来说，而是我们作为开源项目，要做到向前兼容性。比如我现在引用了layotto,但我升级layotto最新版本，我配置文件并不知道需要更改。然后发上线发现挂掉了。

2022-05-12 02:47 UTC, zhenjunMa commented
> > > 这个改动要考虑兼容问题？如果用户升级了Layotto，但配置文件没变，那是不是加载就出问题，可以做成如果没配置type字段就用原先的作为type名字
> > 
> > 
> > 这样子我感觉对于存量用户是不是配置文件会比较混乱啊，统一性没有标准。 其次，这个改动其实对于配置文件来说改动不是很大甚至我们可以实现一个小工具去帮助用户升级配置文件，这些我觉得难度都不是很大
> 
> 这个问题不能用升级难不难来说，而是我们作为开源项目，要做到向前兼容性。比如我现在引用了layotto,但我升级layotto最新版本，我配置文件并不知道需要更改。然后发上线发现挂掉了。

这里其实之前讨论过，主要是考虑到现在 Layotto 还属于相对早一点的阶段，影响范围可控，不想搞那么多兼容代码😜

2022-05-12 07:35 UTC, zhenjunMa approved these changes
LGTM,  thanks!

2022-05-12 07:37 UTC, seeflood commented
We can merge this PR after v0.4 released.

2022-05-12 09:29 UTC, seeflood requested changes
Since this PR introduce an incompatible change, please add more description in the release note.
Github will show your description when releasing new version
![image](https://user-images.githubusercontent.com/26001097/168039013-1b4dc9fe-2b47-4621-933b-d8ca4205eee2.png)

2022-05-12 11:57 UTC, seeflood requested changes
现在 quickstart hang住了，因为demo 里传的 storename 是"etcd"，但是 json 里的 name被改掉了~需要修复下哈
https://github.com/mosn/layotto/runs/6401619750?check_suite_focus=true
![image](https://user-images.githubusercontent.com/26001097/168069549-e2fedfd1-8636-4f0f-813a-a626f1bc7a61.png)

2022-05-12 11:59 UTC, seeflood requested changes

2022-05-12 11:59 UTC, seeflood commented on configs/config_lock_redis.json
> +                        "redis_demo": {
json 里的 name, 如果改成和 type 无关的名字，会不会更好些，能显示出”和组件类型无关、解耦“的感觉~
比如就叫 `my_lock` ，或者 `lock_demo`

2022-05-12 12:02 UTC, seeflood requested changes

2022-05-12 12:02 UTC, seeflood commented on configs/config_apollo_health.json
> +                      "config_store_demo": {
这里应该是 `config_store`不变~ name是下面的 "apollo"

2022-05-13 10:23 UTC, akkw commented
> 现在 quickstart hang住了，因为demo 里传的 storename 是"etcd"，但是 json 里的 name被改掉了~需要修复下哈 https://github.com/mosn/layotto/runs/6401619750?check_suite_focus=true ![image](https://user-images.githubusercontent.com/26001097/168069549-e2fedfd1-8636-4f0f-813a-a626f1bc7a61.png)

好的，我去看一下 之前好像没有发现这个问题

2022-05-13 10:23 UTC, akkw commented on configs/config_apollo_health.json
> +                      "config_store_demo": {
好的

2022-05-13 10:23 UTC, akkw commented on configs/config_lock_redis.json
> +                        "redis_demo": {
好的

2022-05-14 07:19 UTC, seeflood requested changes

2022-05-14 07:19 UTC, seeflood commented on configs/config_apollo.json
> -                      "config_store": {
这里应该还是 `config_store`

2022-05-14 07:19 UTC, seeflood commented on configs/config_apollo_health.json
> +                      "apollo": {
same as above

2022-05-14 07:19 UTC, seeflood commented on configs/config_in_memory.json
> +                        "memory_demo": {
既然是想让name 显得和 type 无关，叫 `state_demo`如何？

2022-05-14 07:19 UTC, seeflood commented on configs/config_in_memory.json
> +                        "memory_demo": {
叫 `lock_demo`如何？

2022-05-14 07:19 UTC, seeflood commented on configs/config_in_memory.json
> +                        "in-memory_demo": {
叫 `pub_sub_demo`如何？

2022-05-14 07:19 UTC, seeflood commented on configs/config_in_memory.json
> +                        "in-memory_demo": {
叫 `sequencer_demo`如何？

2022-05-14 07:39 UTC, akkw commented on configs/config_in_memory.json
> +                        "memory_demo": {
可以

2022-05-14 07:39 UTC, akkw commented on configs/config_in_memory.json
> +                        "in-memory_demo": {
可以

2022-05-15 12:35 UTC, akkw commented
<img width="922" alt="image" src="https://user-images.githubusercontent.com/54854743/168473016-dafc746f-78a1-4ac8-944b-2d39f33107cf.png">
在rpc调用的时候，d.rpcs[mosninvoker.Name] mosninvoker.Name 是字符串mosn 导致
`"grpc_config": {
	"rpcs": {
		"demo": {
		     "type": "mosn",
		     "config": {
		          "channel": [{
		               "size": 16,
		               "protocol": "http",
		               "listener": "egress_runtime_http"
		          }]
	              }
		}
	}
}`
在调用的时候不能实现按name调用，可以讨论一下这个问题吗？

2022-05-16 03:54 UTC, seeflood commented
@akkw 要不 rpc 的这次先不做改造吧，因为 rpc 写死了只能用一个组件

2022-05-16 09:28 UTC, akkw commented
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/54854743/168561635-502f270c-e404-44b3-99be-81e284d1ea0f.png">
这个用例通过不了 排查后发现wasm插件没有加载上，这块该怎么处理

2022-05-16 09:28 UTC, akkw commented
> @akkw要不 rpc 的这次先不做改造吧，可以保留原样，因为 rpc 写死了只能用一个组件

可以

2022-05-16 12:50 UTC, zhenjunMa commented
@akkw 现在就差wasm的集成测试跑不过了，报错信息如下：

![image](https://user-images.githubusercontent.com/28104581/168594898-712afc5f-4f79-4aec-9740-9e4270bd8206.png)
应该是不不兼容改动引起的，因此还需要对下面三个地方的hardcode部分进行修改

Go版的wasm示例：

https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/golang/server/function.go#L68

Rust版的wasm示例：
https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/rust/server/src/lib.rs#L37

AssemblyScript版的wasm示例
https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/assemblyscript/assembly/server.ts#L27


最后还需要重新编译一遍wasm文件，来覆盖掉`demo/faas/code/golang/server/function_2.wasm` ，因为集成测试是以这个为例运行的，其他两版只需修改，不用重新编译。

编译命令为：
```
tinygo build -o function_2.wasm -scheduler=none -target=wasi -wasm-abi=generic -tags 'abi_010' function.go
```

2022-05-17 02:31 UTC, akkw commented
> 

我尝试一下这种做法

2022-05-17 02:41 UTC, akkw commented
> @akkw 现在就差wasm的集成测试跑不过了，报错信息如下：
> 
> ![image](https://user-images.githubusercontent.com/28104581/168594898-712afc5f-4f79-4aec-9740-9e4270bd8206.png) 应该是不兼容改动引起的，因此还需要对下面三个地方的hardcode部分进行修改
> 
> Go版的wasm示例：
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/golang/server/function.go#L68
> 
> Rust版的wasm示例：
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/rust/server/src/lib.rs#L37
> 
> AssemblyScript版的wasm示例
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/assemblyscript/assembly/server.ts#L27
> 
> 最后还需要重新编译一遍wasm文件，来覆盖掉`demo/faas/code/golang/server/function_2.wasm` ，因为集成测试是以这个为例运行的，其他两版只需修改，不用重新编译。
> 
> 编译命令为：
> 
> ```
> tinygo build -o function_2.wasm -scheduler=none -target=wasi -wasm-abi=generic -tags 'abi_010' function.go
> ```
我尝试一下

2022-05-17 02:42 UTC, akkw commented
> @zhenjunMa @akkw 听起来有点麻烦，如果wasm这个case不好改的话，就把faas demo 用的json 的name 回退、还叫 `redis` 呢？ ![image](https://user-images.githubusercontent.com/26001097/168607393-7b4e6c57-b98d-4001-bdca-c6efdc7f93f2.png)
> 
> 当然，两种办法都行， @akkw 看你喜欢哪种

我先用第一种尝试一下吧，最大程度上保证配置风格统一

2022-05-17 02:52 UTC, seeflood commented
@akkw ok.
可以稍微补点单测，避免codecov 因为覆盖率下降而报错~

2022-05-17 08:10 UTC, akkw commented
> @akkw 现在就差wasm的集成测试跑不过了，报错信息如下：
> 
> ![image](https://user-images.githubusercontent.com/28104581/168594898-712afc5f-4f79-4aec-9740-9e4270bd8206.png) 应该是不兼容改动引起的，因此还需要对下面三个地方的hardcode部分进行修改
> 
> Go版的wasm示例：
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/golang/server/function.go#L68
> 
> Rust版的wasm示例：
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/rust/server/src/lib.rs#L37
> 
> AssemblyScript版的wasm示例
> 
> https://github.com/mosn/layotto/blob/289b7f12eb8879762240bb9c9ae8fc926c3d3f7f/demo/faas/code/assemblyscript/assembly/server.ts#L27
> 
> 最后还需要重新编译一遍wasm文件，来覆盖掉`demo/faas/code/golang/server/function_2.wasm` ，因为集成测试是以这个为例运行的，其他两版只需修改，不用重新编译。
> 
> 编译命令为：
> 
> ```
> tinygo build -o function_2.wasm -scheduler=none -target=wasi -wasm-abi=generic -tags 'abi_010' function.go
> ```
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/54854743/168762247-3ff052ef-36d5-4523-93ad-cff7d9b7470c.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/54854743/168761954-4eb99e6d-6326-45be-bae7-0fe8d6b89c16.png">
这样子貌似不行，wasm plugin 加载有错误 好像是
<img width="792" alt="image" src="https://user-images.githubusercontent.com/54854743/168762367-36e0a74e-b68e-4a03-8195-78abf19d218e.png">
route.routes 这个map 是空的

2022-05-18 14:43 UTC, zhenjunMa approved these changes

2022-05-19 03:39 UTC, seeflood requested changes

2022-05-19 03:39 UTC, seeflood commented on configs/config_redis.json
>                          }
![image](https://user-images.githubusercontent.com/26001097/169198720-4c0d0b5c-1fb3-4824-9699-9c9586793113.png)
这里不太对哈，应该是:
```json
"hellos": {
  "quick_start_demo": {
    "type": "helloworld",
    "hello": "greeting"
  }
```

2022-05-19 03:39 UTC, seeflood commented on configs/config_redis.json
> +                          "Type": "redis",
`Type` -> `type`

2022-05-19 03:44 UTC, seeflood requested changes

2022-05-19 03:44 UTC, seeflood commented on docs/en/start/sequencer/start.md
> + ./client -s "config_sequencer_etcd"
config_sequencer_etcd  -> sequencer_demo

2022-05-19 10:08 UTC, seeflood requested changes

2022-05-19 10:08 UTC, seeflood commented on pkg/runtime/runtime.go
> +		h, err := m.helloRegistry.Create(config.Type)
I suggest we modify all the `name` fields in all the `registry.go` to `type`
![image](https://user-images.githubusercontent.com/26001097/169268844-544ce98c-1cf3-4556-a03d-8aa092324ca2.png)

2022-05-19 10:12 UTC, seeflood requested changes

2022-05-19 10:12 UTC, seeflood commented on configs/config_integration_redis_etcd.json
> +                        "demo": {
We have to keep it `mosn`

2022-05-19 10:41 UTC, seeflood requested changes

2022-05-19 10:41 UTC, seeflood commented on components/configstores/types.go
> +	Type      string            `json:"type"`
Please update docs under https://mosn.io/layotto/#/zh/component_specs/overview 
and https://mosn.io/layotto/#/en/component_specs/overview

For example, we should update https://mosn.io/layotto/#/en/component_specs/state/common
![image](https://user-images.githubusercontent.com/26001097/169275081-3585e64e-5ff0-4fe1-a65e-43d1621f020b.png)

2022-05-19 12:05 UTC, seeflood requested changes

2022-05-19 12:05 UTC, seeflood commented on configs/config_in_memory.json
> +                            "type": "in-memory",
custom component 这个有点特殊，以前就有"type" 字段，见 https://mosn.io/layotto/#/zh/component_specs/custom/common?id=%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6%e7%bb%93%e6%9e%84
旧配置的数据结构是 name 放到 type 下面：
![image](https://user-images.githubusercontent.com/26001097/169286884-d44cd1df-ff06-47c6-b148-4db8faecb5d3.png)
我在你的分支改一下吧，感觉可以把以前的`type`改个名字，改成 `kind`

2022-05-19 12:05 UTC, seeflood commented on pkg/runtime/runtime_test.go
> +				Type: "mock",
UT 里的 name 和 type 最好不一样，这样更能测出问题~

2022-05-19 12:09 UTC, seeflood requested changes

2022-05-19 12:09 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		testClient.TryLock(ctx, &request)
ut 需要加一下断言，不然没法发现问题

2022-05-19 12:09 UTC, seeflood commented on pkg/runtime/secretstores/factory_test.go
> +		return secret.FakeSecretStore{}
ut 需要加一下断言，不然没法发现问题

2022-05-19 12:09 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		testClient.Unlock(ctx, &request)
ut 需要加一下断言，不然没法发现问题

2022-05-19 12:52 UTC, seeflood commented on configs/config_in_memory.json
> +                            "type": "in-memory",
done

2022-05-19 12:55 UTC, seeflood commented on configs/config_redis.json
> +                          "Type": "redis",
fixed

2022-05-19 12:57 UTC, seeflood commented on configs/config_redis.json
>                          }
fixed

2022-05-19 13:00 UTC, seeflood commented on configs/config_integration_redis_etcd.json
> +                        "demo": {
fixed

2022-05-19 13:02 UTC, seeflood commented
我们在你的分支做了很多修改，记得别 git push -f 覆盖哈

2022-05-19 13:34 UTC, akkw commented on components/configstores/types.go
> +	Type      string            `json:"type"`
好的

2022-05-19 14:06 UTC, akkw commented
我本地的go.mod和go.sum 改动了需要提上来吗

2022-05-19 14:08 UTC, seeflood commented
@akkw 你先 git pull 拉到最新代码，然后就可以正常 push了，记得别 push -f 强行覆盖远端的代码就行

2022-05-19 14:27 UTC, akkw commented on pkg/runtime/runtime_test.go
> +						Type:     compName,
`Type:     compName,`

这里的compName值已经是etcd了

2022-05-19 14:52 UTC, akkw commented on docs/en/start/sequencer/start.md
> + ./client -s "config_sequencer_etcd"
这里找到原因了，是因为程序没有进行panic,直接return了

2022-05-19 14:55 UTC, akkw commented on docs/en/start/sequencer/start.md
> + ./client -s "config_sequencer_etcd"
> config_sequencer_etcd -> sequencer_demo
> 
> 我得查一下，为啥传参错了、但 CI没报错

这里我处理了

2022-05-19 15:12 UTC, akkw commented on pkg/runtime/runtime.go
> +		h, err := m.helloRegistry.Create(config.Type)
> type是go的一个关键字，叫typeName合适吗？

type是go的一个关键字，叫typeName合适吗？

2022-05-21 03:19 UTC, azhsmesos commented
> 

啊啊 才看见，这个回去我在弄，我之前因为本地启动项目产生了client文件，后面我好像-f覆盖了，等我回去重新pull 一下 重新push

2022-05-21 03:26 UTC, azhsmesos commented
> 我们在你的分支做了很多修改，记得别 git push -f 覆盖哈

可能已经覆盖了，我重新从master pull 最新的过来，在重新push 可以吗，我之前因为client太大（github无法上传超过100M的，但是我没注意这个问题，我就push -f了，后面忘了改push命令了，我直接 快捷键 ^ 的方式采用之前的命令，估计已经push -f了...

2022-05-21 05:55 UTC, seeflood commented
@azhsmesos 额，你是不是理解错啦，我是和 akkw 说他这个分支记得别 git push -f ，你的pr应该是另一个分支，和这个pr 不是一个分支，不影响啊

2022-05-23 06:11 UTC, seeflood requested changes

2022-05-23 06:11 UTC, seeflood commented on components/hello/registry.go
>  type HelloFactory struct {
![image](https://user-images.githubusercontent.com/26001097/169754245-6751128a-7818-43e6-a5de-684699852f3a.png)
这个文件里，其他name 字段也要改成 componentType 哈

2022-05-23 06:11 UTC, seeflood commented on pkg/runtime/bindings/registry.go
>  type bindingsRegistry struct {
同上。其他 registry.go 也是

2022-05-23 06:45 UTC, seeflood commented on pkg/runtime/runtime_test.go
> +						Type:     compName,
我刚在你的分支做了修改，把name和type改成了不一样的字符串，以便能更好的测试~
done

2022-05-23 07:10 UTC, seeflood commented on components/configstores/types.go
> +	Type      string            `json:"type"`
这个似乎没修复，我重新打开了哈

2022-05-23 07:15 UTC, seeflood requested changes

2022-05-23 07:15 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +			ResourceId: "lock_test",
要传 StoreName，我在你分支改一下吧

2022-05-23 07:27 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +			ResourceId: "lock_test",
done

2022-05-23 07:29 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +	t.Run("unlock with different owner failed", func(t *testing.T) {
@akkw 测试用例的名字最好能概括下这个测试做了啥、最后成功还是失败了。我直接改了哈，供参考

2022-05-23 07:32 UTC, seeflood requested changes

2022-05-23 07:32 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +				Status: runtimev1pb.UnlockResponse_Status(lock.LOCK_BELONG_TO_OTHERS),
改成用 pb 里的枚举值吧，UnlockResponse_LOCK_BELONG_TO_OTHERS

2022-05-23 07:32 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +			Status: runtimev1pb.UnlockResponse_Status(lock.LOCK_UNEXIST),
同上，改成用 pb 里的枚举值吧

2022-05-23 07:32 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +				Status: runtimev1pb.UnlockResponse_Status(lock.SUCCESS),
同上，改成用 pb 里的枚举值吧

2022-05-23 07:32 UTC, seeflood commented on sdk/go-sdk/go.mod
> +	mosn.io/layotto/components v0.0.0-20220519092435-5db44ed16f38
sdk 不应该依赖组件包哈

2022-05-24 04:17 UTC, seeflood commented
@akkw 要不我直接在你的分支修改、尽快合并吧，我担心再不合并，会有各种冲突，要花很多时间修冲突~
方便记个 “补充文档” 的 issue么，文档可以后面再提 pr 修

2022-05-24 13:00 UTC, seeflood requested changes

2022-05-24 13:00 UTC, seeflood commented on components/custom/registry.go
> +	Register(compType string, factorys ...*ComponentFactory)
compType -> kind

2022-05-24 13:00 UTC, seeflood commented on components/custom/registry.go
> +func (r *componentRegistry) Register(compType string, fs ...*ComponentFactory) {
compType -> kind

2022-05-24 13:00 UTC, seeflood commented on components/custom/registry.go
> +func (r *componentRegistry) Create(compType, name string) (Component, error) {
Create( kind, compType string)

2022-05-24 14:02 UTC, seeflood requested changes

2022-05-24 15:47 UTC, seeflood commented on components/custom/registry.go
> +func (r *componentRegistry) Create(compType, name string) (Component, error) {
这个是因为之前 `custom_component` 已经有个 component type 了，这次又加一个 type，我想着得把以前的 type改个名字：
![image](https://user-images.githubusercontent.com/26001097/170077569-30c704e4-f6e3-4e92-87b8-25927f02afd5.png)
https://mosn.io/layotto/#/zh/component_specs/custom/common

至于叫 kind 还是叫别的，比如叫 service 都行
我在你分支里改了一些代码、改成了叫 kind，但是刚发现之前有些代码叫 service

2022-05-25 02:35 UTC, seeflood commented on components/custom/registry.go
> +func (r *componentRegistry) Create(compType, name string) (Component, error) {
这个我看没改，重新打开了哈

2022-05-25 02:47 UTC, seeflood requested changes

2022-05-25 02:47 UTC, seeflood commented on pkg/runtime/runtime.go
> +			log.DefaultLogger.Errorf("[runtime] Your required component type %s is not supported.Please check your configuration", kind)
"component type" 这里日志也要改下

2022-05-25 02:47 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +	} else {
if 里会 return 的话，就不用写 else了

2022-05-25 02:47 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +		} else {
if 里会 return 的话，就不用写 else了

2022-05-25 02:47 UTC, seeflood commented on sdk/go-sdk/client/client_test.go
> +	} else {
if 里会 return 的话，就不用写 else了

2022-05-25 02:47 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		assert.True(t, lock.Success, true)
assert.True(t, lock.Success)

2022-05-25 02:47 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		assert.True(t, lock.Success, true)
assert.True(t, lock.Success)

2022-05-25 03:01 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		assert.True(t, lock.Success, true)
我push 修了

2022-05-25 03:01 UTC, seeflood commented on sdk/go-sdk/client/lock_test.go
> +		assert.True(t, lock.Success, true)
我push 修了

2022-05-25 03:06 UTC, seeflood commented
@mosn/layotto-commiter  @mosn/layotto-pmc 这个 PR 先帮忙合并吧，一些遗留小问题不影响功能，我提新的PR修复。正好我要重新跑一遍 linter 检查

2022-05-25 03:08 UTC, seeflood approved these changes
lgtm

2022-05-25 03:22 UTC, wenxuwan approved these changes

2022-05-25 03:24 UTC, merged

2022-05-25 03:25 UTC, seeflood commented
感谢贡献！！！辛苦了！