docs: webassembly code analysis
mosn/layotto pull request #575
Opened 2022-05-17 17:52 UTC by rayowang

**What this PR does**:
webassembly code analysis
**Which issue(s) this PR fixes**:
#427

2022-05-18 04:18 UTC, seeflood commented
I wonder which tool you used to draw these diagrams. These diagrams look very professional, much better than mine 😢

2022-05-19 02:57 UTC, seeflood commented
ok. I used processon before, but the diagrams I drawed are too ugly...... 😢 
![](https://mosn.io/layotto/img/lock/img.png)

2022-05-24 09:51 UTC, zhenjunMa requested changes

2022-05-24 09:51 UTC, zhenjunMa commented on docs/zh/blog/code/webassembly/index.md
> +### Faas模式
Faas -> FaaS

2022-05-24 09:51 UTC, zhenjunMa commented on docs/zh/blog/code/webassembly/index.md
> +回过头来再看 WASM 的特性：字节码有与机器码相匹敌的性能；沙箱中执行保证良好的隔离性和安全性；编译后跨平台、易分发和加载运行；具备轻量且多语言开发的灵活性，似乎天然的就适合做 Faas。
Faas -> FaaS

2022-05-24 09:51 UTC, zhenjunMa commented on docs/zh/blog/code/webassembly/index.md
> +回过头来再看 WASM 的特性：字节码有与机器码相匹敌的性能；沙箱中执行保证良好的隔离性和安全性；编译后跨平台、易分发和加载运行；具备轻量且多语言开发的灵活性，似乎天然的就适合做 Faas。
下面几个也都改成FaaS

2022-05-24 09:51 UTC, zhenjunMa commented on docs/zh/blog/code/webassembly/index.md
> +Layotto Webassemly 虽然涉及较多 WASM 相关的基础知识，但通过示例由浅入深，循序渐进也不难理解。最后整体看一下 WASM 技术，可以看到它已经被应用到Web前端、Serverless、游戏场景、边缘计算、服务网格等很多领域，甚至就连 Docker 之父 Solomon Hykes 在前不久都表示: "如果 WASM 这个技术在2008年就有的话，我就不搞Docker了"（后
Webassemly -> WebAssembly

2022-05-26 03:28 UTC, zhenjunMa submitted a review, later dismissed
Thanks!

2022-05-26 06:40 UTC, seeflood reviewed
@rayowang Hi , I uploaded the images to CDN and submitted a PR to your branch
Please review https://github.com/rayowang/layotto/pull/1

2022-05-26 08:13 UTC, seeflood commented
It's weird that this PR didn't update automatically after merging https://github.com/rayowang/layotto/pull/1 😢 
@rayowang Could u please update this PR

2022-05-26 08:21 UTC, rayowang commented
> It's weird that this PR didn't update automatically after merging [rayowang#1](https://github.com/rayowang/layotto/pull/1) 😢 @rayowang Could u please update this PR

I was wondering about this problem just now, and later found out that I have two similar branch names, so the branch of this pr is wasm_code_analysis, not webassembly_code_analysis.  So now, do I cherry-pick the changes or do you pr to the wasm_code_analysis branch?

2022-05-26 08:30 UTC, seeflood commented
@rayowang OK you can cherry pick those changes

2022-05-26 08:49 UTC, rayowang commented
> @rayowang OK you can cherry pick those changes

ok, done.

2022-05-26 08:51 UTC, seeflood approved these changes
lgtm. Thanks!

2022-05-26 08:52 UTC, zhenjunMa approved these changes

2022-05-26 09:05 UTC, merged