translate the zh to en
mosn/layotto pull request #581
Opened 2022-05-19 08:39 UTC by NTH19

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #545 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-05-19 12:25 UTC, NTH19 commented
I have already signed the CLA.

2022-05-19 12:29 UTC, seeflood commented
> I have already signed the CLA.

Ok. 
I closed and reopened the PR to rerun the workflow

2022-05-19 12:48 UTC, Xunzhuo requested changes
Some minor changes, thanks @NTH19

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> +This document explains Layotto's  four workflows in Github ：
remove the extra space here

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> +The workflow contains one or more tasks，It improves the standardization and security of the code in layotto，simplifies repetitive steps of development / build / release.The following is a detailed ex
Need a space here: `release.The`

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> ++ Linux AMD64 Artifact :Build linux amd64binary verification for code
need a space here

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> +        branches: "*" commit PR
create or start a PR

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> +Layotto Env Pipeline Task Trigger Method：
Layotto Env Pipeline Task Trigger Method -> Layotto Env Pipeline Task Trigger Events

2022-05-19 12:48 UTC, Xunzhuo commented on docs/en/development/github-workflows.md
> ++ License Validation (Verification of license )
remove the extra space here

2022-05-19 13:17 UTC, NTH19 commented
> Some minor changes, thanks @NTH19

Is there a description file for the documentation specification ? @Xunzhuo

2022-05-20 11:12 UTC, Xunzhuo approved these changes

2022-05-20 11:12 UTC, Xunzhuo commented
lgtm

2022-05-20 15:07 UTC, seeflood approved these changes
lgtm. Thanks!

2022-05-20 15:08 UTC, merged