mix pubsub demo
mosn/layotto pull request #594
Opened 2022-05-22 01:40 UTC by gdutChenxj

**What this PR does**:
mix pubsub demo

**Which issue(s) this PR fixes**:

Fixes [#584](https://github.com/mosn/layotto/issues/584)

2022-05-22 14:06 UTC, gdutChenxj commented
- i have  signed CLA but the status is not sync automatically
-  to merge all pubsub demo, some folder will be deleted and it make  an error when `Quickstart Validation`  exec cmd `cd /home/runner/work/layotto/layotto/demo/pubsub/redis/server/`，the script seem to be build on the workflow server，i think it need somebody to update the script or ignore the validation error

2022-05-22 15:24 UTC, seeflood commented
>i have signed CLA but the status is not sync automatically

Fixed. I closed and reopened this PR to rerun the workflow .

>to merge all pubsub demo, some folder will be deleted and it make an error when Quickstart Validation exec cmd cd /home/runner/work/layotto/layotto/demo/pubsub/redis/server/，the script seem to be build on the workflow server，i think it need somebody to update the script or ignore the validation error

Yes you are right :)
The quickstart doc http://localhost:3000/#/en/start/pubsub/start  and http://localhost:3000/#/zh/start/pubsub/start used the redis demo:
![image](https://user-images.githubusercontent.com/26001097/169702431-25eb900e-73a2-4076-9730-8685b4e1784f.png)
![image](https://user-images.githubusercontent.com/26001097/169702445-d4dc049a-248e-432b-bb5d-15ab3bc166c3.png)
And Layotto runs these quickstart document in the workflow, see http://localhost:3000/#/zh/development/test-quickstart

So, could u help modify the documentation in this PR?
Just modify the doc to use the new demo code.
If you don't know how to fix it after reading the doc, I can help submit a PR to your branch to fix it :)

2022-05-23 06:52 UTC, gdutChenxj commented
i will update the doc for the new demo

2022-05-25 11:36 UTC, gdutChenxj commented
@seeflood  I have updated the quick start doc and it can work well in my local test. But there is a confliction need somebody with write access to handle.

2022-05-26 03:12 UTC, seeflood commented
> @seeflood I have updated the quick start doc and it can work well in my local test. But there is a confliction need somebody with write access to handle.

Thanks ! I just saw this message.
You have the permission to resolve the conflicts.
To resolve them, you can:
1.  Merge main branch into your branch, on your computer. The IDE will guide you to fix conflicts
2. After all resolved and merged, you just push your new code to your github repo.

2022-05-26 04:29 UTC, seeflood requested changes

2022-05-26 04:29 UTC, seeflood commented on docs/en/start/pubsub/start.md
> + ./subscriber -s redis
```suggestion
 ./subscriber -s pub_subs_demo
```

2022-05-26 04:29 UTC, seeflood commented on docs/en/start/pubsub/start.md
> + ./publisher -s redis
```suggestion
 ./publisher -s pub_subs_demo
```

2022-05-26 04:29 UTC, seeflood commented on docs/zh/start/pubsub/start.md
> + ./subscriber -s redis
```suggestion
 ./subscriber -s pub_subs_demo
```

2022-05-26 04:29 UTC, seeflood commented on docs/zh/start/pubsub/start.md
> + ./publisher -s redis
```suggestion
 ./publisher -s pub_subs_demo
```

2022-05-26 04:31 UTC, seeflood requested changes

2022-05-26 04:31 UTC, seeflood commented on demo/pubsub/README.md
> +```go
~~~suggestion
```shell
~~~

2022-05-26 04:31 UTC, seeflood commented on demo/pubsub/README.md
> +/.subscriber
```suggestion
/.subscriber -s pub_subs_demo
```

2022-05-26 04:31 UTC, seeflood commented on demo/pubsub/README.md
> + ./publisher
```suggestion
 ./publisher -s pub_subs_demo
```

2022-05-26 04:59 UTC, gdutChenxj commented
@seeflood all conversations are resolved

2022-05-26 05:54 UTC, seeflood approved these changes
lgtm. Thanks for your contribution and welcome to the community !

2022-05-26 05:59 UTC, zhenjunMa approved these changes

2022-05-26 06:00 UTC, merged