feat: implement sequencer api with mysql
mosn/layotto pull request #605
Opened 2022-05-25 03:38 UTC by GimmeCyy

**What this PR does**:
add sequencer api component by mysql

**Which issue(s) this PR fixes**:
#489

2022-05-27 05:30 UTC, seeflood commented
Thanks!
To fix the CI error, you can `make format` and them git commit the changes

2022-05-29 16:22 UTC, ZLBer commented
@GimmeCyy I answered you  below https://github.com/mosn/layotto/pull/509

2022-06-03 08:19 UTC, ZLBer approved these changes
finally add some docs  below `docs/en/component_specs/sequencer` `docs/zh/component_specs/sequencer`

2022-06-03 08:55 UTC, seeflood requested changes

2022-06-03 08:55 UTC, seeflood commented on cmd/layotto/main.go
> +			runtime_sequencer.NewFactory("mysql", func() sequencer.Store {
Could u add it into the `cmd/layotto_multiple_api/main.go` too ?

2022-06-08 03:36 UTC, seeflood requested changes

2022-06-08 03:36 UTC, seeflood commented on docs/en/component_specs/sequencer/mysql.md
> +## metadata fields
Please add this doc into the sidebar.
See https://mosn.io/layotto/#/zh/development/contributing-doc?id=_3-%e6%96%b0%e5%a2%9e%e6%96%87%e6%a1%a3%e9%9c%80%e8%a6%81%e5%81%9a%e5%93%aa%e4%ba%9b%e4%ba%8b
![image](https://user-images.githubusercontent.com/26001097/172526288-aecc0c66-fe01-40a0-a835-0c6ac348718a.png)

2022-06-08 03:36 UTC, seeflood commented on docs/zh/component_specs/sequencer/mysql.md
> +## 配置项说明
Please add this doc into the sidebar.
See https://mosn.io/layotto/#/zh/development/contributing-doc?id=_3-%e6%96%b0%e5%a2%9e%e6%96%87%e6%a1%a3%e9%9c%80%e8%a6%81%e5%81%9a%e5%93%aa%e4%ba%9b%e4%ba%8b
![image](https://user-images.githubusercontent.com/26001097/172526288-aecc0c66-fe01-40a0-a835-0c6ac348718a.png)

2022-06-11 02:41 UTC, ZLBer commented on components/sequencer/mysql/mysql.go
> +		_, err := begin.Exec("INSERT INTO ?(sequencer_key, sequencer_value, version) VALUES(?,?,?)", metadata.TableName, req.Key, Value, Version)
这里会有并发插入问题吗？

2022-06-12 15:08 UTC, ZLBer commented
@GimmeCyy 本地的锁似乎是没用的，layotto可能是多机部署。可以先交流下再写代码~

2022-06-19 15:02 UTC, ZLBer approved these changes
LGTM

2022-07-18 06:34 UTC, seeflood approved these changes
lgtm.

2022-07-18 06:39 UTC, zhenjunMa approved these changes

2022-07-18 07:03 UTC, merged

2022-07-18 07:04 UTC, seeflood commented
@GimmeCyy Thanks for your help!