translation: test-quickstart
mosn/layotto pull request #633
Opened 2022-06-08 09:52 UTC by LXPWing

add en test-quickstart.md #438

2022-06-08 13:34 UTC, seeflood commented
Good English 👍

2022-06-08 15:56 UTC, seeflood requested changes

2022-06-08 15:56 UTC, seeflood commented on docs/_sidebar.md
> +    - [Automate testing of Quickstart documentation with tools](en/development/test-quickstart.md)
We can make the directory structure same with [chinese doc](https://mosn.io/layotto/#/zh/development/contributing-doc) :
![image](https://user-images.githubusercontent.com/26001097/172662614-d771395e-bab0-4d57-a6e6-1015f9315a57.png)

2022-06-09 02:19 UTC, LXPWing commented on docs/_sidebar.md
> +    - [Automate testing of Quickstart documentation with tools](en/development/test-quickstart.md)
update

2022-06-09 03:53 UTC, seeflood requested changes

2022-06-09 03:53 UTC, seeflood commented on docs/en/development/test-quickstart.md
> +Wrapped up script.
I feel this sentence has some grammatical problems 🤔 
How about this:
~~~
Use the tool to execute all shell scripts in a markdown file sequentially, i.e. all scripts wrapped in:

```shell
```
~~~

2022-06-09 03:53 UTC, seeflood commented on docs/en/development/test-quickstart.md
> +Wrapped up script.
Same as above

2022-06-09 07:23 UTC, LXPWing commented on docs/en/development/test-quickstart.md
> +Wrapped up script.
‘i.e.’ , What does it mean?

2022-06-09 07:27 UTC, seeflood commented on docs/en/development/test-quickstart.md
> +Wrapped up script.
It means "that is","也就是，即"
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD/ie
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%B9%81%E4%BD%93/i-e

2022-06-09 07:52 UTC, seeflood requested changes

2022-06-09 07:52 UTC, seeflood commented on docs/en/development/test-quickstart.md
> +~~~markdown
```suggestion
Note: The script wrapped in `bash` blocks will NOT be run.
```

2022-06-09 08:25 UTC, seeflood approved these changes
lgtm

2022-06-10 06:06 UTC, zhenjunMa approved these changes

2022-06-10 06:09 UTC, wenxuwan approved these changes

2022-06-10 06:16 UTC, merged

2022-06-10 06:16 UTC, seeflood commented
Thanks!