docs(en): add en operation doc
mosn/layotto pull request #656
Opened 2022-06-16 02:50 UTC by palering

**What this PR does**:  translate the operation guide into english

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-06-16 03:10 UTC, seeflood requested changes

2022-06-16 03:10 UTC, seeflood commented on docs/en/operation/README.md
> +### Deploy Layotto from release binaries
Deploy Layotto using released binaries

2022-06-16 03:10 UTC, seeflood commented on docs/en/operation/README.md
> +To run, download or build the binary for your platform, then exec it. Refer to the [Quick start](en/start) guide.
这句话看起来不通顺？

2022-06-16 03:10 UTC, seeflood commented on docs/en/operation/README.md
> +It's not contain a `config.json` configuration file in the image, you can mount your own configuration file into the `/runtime/configs/` directory of the image. For example.
It's not contain
语法不对吧

2022-06-16 03:11 UTC, seeflood commented
Thanks for your contribution!
Please sign the cla first

2022-06-16 03:15 UTC, palering commented on docs/en/operation/README.md
> +It's not contain a `config.json` configuration file in the image, you can mount your own configuration file into the `/runtime/configs/` directory of the image. For example.
It does not contain

2022-06-16 03:26 UTC, palering commented on docs/en/operation/README.md
> +To run, download or build the binary for your platform, then exec it. Refer to the [Quick start](en/start) guide.
那直接点 You can start Layotto directly via executing the binary file

2022-06-16 04:26 UTC, palering commented
> Thanks for your contribution! Please sign the cla first

In the wehsite<http://cla.sofastack.tech/>, the msg `Thank you for signing the Agreement!`  has been shown.But the status of  the mosn-bot/cla has not been updated, so what should I do now?

2022-06-16 06:19 UTC, seeflood commented
> > Thanks for your contribution! Please sign the cla first
> 
> In the wehsitehttp://cla.sofastack.tech/, the msg `Thank you for signing the Agreement!` has been shown.But the status of the mosn-bot/cla has not been updated, so what should I do now?

Now it's updated :)

2022-06-16 09:32 UTC, seeflood requested changes

2022-06-16 09:32 UTC, seeflood commented on docs/en/operation/README.md
> +- [OpenKruise hot upgrades in-place](https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/)
```suggestion
- [Hot upgrade using OpenKruise](https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/)
```

2022-06-16 11:03 UTC, palering commented on docs/en/operation/README.md
> +There is no essential difference, just pay attention to the version, the versions Layotto and MOSN must correspond to each other.
这样如何 the versions between Layotto and MOSN must correspond to each other

2022-06-16 11:03 UTC, palering commented on docs/en/operation/README.md
> +- [Smooth upgrade with automatic migrate existing persistent connections](https://mosn.io/en/docs/concept/smooth-upgrade/)
ok，这个当时看了文章中摘要的后半句

2022-06-16 16:46 UTC, seeflood approved these changes
lgtm

2022-06-17 01:59 UTC, wenxuwan approved these changes

2022-06-17 02:04 UTC, merged