feat:implement snowflake algorithm
mosn/layotto pull request #659
Opened 2022-06-18 08:36 UTC by azhsmesos

解决两个问题：
 1.时钟回拨，没有采用redis的方式，而是本地保存当前最大timestart，每次启动时就找到这台机器上面的max_time自增就好了，保持逻辑时钟
 2.跨毫秒起始值起始每次默认都是0，这会导致末尾是偶数不方便取余，所以采用random的方式选取1～3的随机数

2022-06-18 12:31 UTC, seeflood requested changes
need to implement GetSegment

2022-06-18 12:32 UTC, seeflood commented
action:
调研一下要不要接存储
调研一下时钟回拨问题

2022-06-18 12:33 UTC, seeflood requested changes

2022-06-18 12:33 UTC, seeflood commented on components/sequencer/snowflake/sequencer_snowflake.go
> +	machineRoomIdBits   = 5                                                      // 机房id 五位数
Need english comments

2022-06-19 15:15 UTC, ZLBer commented
@seeflood 
This subject participated in GLCC.I think we should follow the rules of GLCC.
PR should not be submitted now.It's not fair.
We should choose the candidate from all students who have submitted their proposal.

2022-06-20 00:33 UTC, seeflood commented
@ZLBer Agreed. We should follow the rules and make it fair.
@azhsmesos Thanks for your contribution, but please submit a GLCC proposal and wait for the approval before submitting this PR.
We have to close this PR and wait for the GLCC process.
For now, you can continue with other PR, like #554 and #137

2022-06-20 00:37 UTC, closed without merging