[GLCC]Integrate test
mosn/layotto pull request #702
Opened 2022-07-07 10:49 UTC by bxiiiiii

**What this PR does**:
Add more components and api features in integrate test
**Which issue(s) this PR fixes**:

Fixes #415

2022-07-30 05:06 UTC, zhenjunMa requested changes

2022-07-30 05:06 UTC, zhenjunMa commented on sdk/go-sdk/test/runtime/zookeeper_integrate_test.go
> +
在ZK的集成测试中加一个State API的用例以及一个Configuration的用例

2022-07-30 05:06 UTC, zhenjunMa commented on sdk/go-sdk/test/runtime/etcd_integrate_test.go
> +
在ZK的集成测试中加一个State API的用例

2022-07-30 05:45 UTC, zhenjunMa commented
另外关于`zkCreateZNode.sh` 脚本里的内容本质上是由于Layotto实现有问题导致的，详细信息可用参考 #747 
感兴趣也可以fix一下🤝

2022-07-30 07:10 UTC, bxiiiiii commented on sdk/go-sdk/test/runtime/etcd_integrate_test.go
> +		"feature": "test2",
加了tag之后就不能整个结构体的进行比较，我只想到一条一条进行比较，还有别的方法吗

2022-07-30 13:40 UTC, bxiiiiii commented on sdk/go-sdk/test/runtime/etcd_integrate_test.go
> +		"feature": "test2",
![1659188380562](https://user-images.githubusercontent.com/75570810/181917014-b35c59eb-e6db-4a52-bf07-145dd22a07c0.jpg)

2022-08-12 06:00 UTC, zhenjunMa approved these changes
LGTM

2022-08-12 06:22 UTC, seeflood commented on sdk/go-sdk/test/runtime/integrate_test.go
> +			stateKey = "/zookeeper"
Why adding special check for zookeeper here? Can we remove this check and make client code independent of components?

2022-08-12 06:36 UTC, seeflood requested changes

2022-08-12 06:36 UTC, seeflood commented on sdk/go-sdk/test/runtime/integrate_test.sh
>  go test -p 1 -v ./...
hi, 其实 [demo 目录下](https://github.com/mosn/layotto/tree/main/demo) 有很多现成的demo、可以当测试用例，所以能否把demo下的用例也添加到这里运行~

Q: 为啥这样做?
- 如果像现在这样，需要维护两套测试代码，一份是这里的 `integrate_test.go`，一份是 demo目录下的代码；
- 如果能直接拿 demo 下的代码当集成测试跑，就能减少代码冗余


Q: 如何改？
举个例子，添加以下shell 脚本，运行 `demo/lock/common/` 下的代码

```
 cd demo/lock/common/
 go build -o client

  processes="lock_demo lock_demo2 lock_demo3 lock_demo4"
  for key in ${processes}; do
	 ./client -s $key
  done
```

2022-08-12 06:42 UTC, seeflood requested changes

2022-08-12 06:42 UTC, seeflood commented on sdk/go-sdk/test/runtime/integrate_test.sh
>  go test -p 1 -v ./...
以及，目前该集成测试不会测 pubsub、secret，能否添加一下对这俩api 的测试~
可以用 demo 目录下的代码作为测试用例

2022-08-13 07:27 UTC, bxiiiiii commented on sdk/go-sdk/test/runtime/integrate_test.go
> +			stateKey = "/zookeeper"
是因为zookeeper向外暴露的是znode的接口，key为znode的path。而client这边不支持znode的create操作，并且SaveState是调用dapr的，不能进行修改。zookeeper默认会有一个/zookeeper的znode，所以 stateKey 需要进行修改。

2022-08-13 09:55 UTC, seeflood commented on sdk/go-sdk/test/runtime/integrate_test.go
> +			stateKey = "/zookeeper"
@bxiiiiii @zhenjunMa 我记得 zk的组件配置是能配“默认前缀”的，看下能否在json里配上默认前缀，解决这个问题？

https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-zookeeper/#spec-metadata-fields

![image](https://user-images.githubusercontent.com/26001097/184478738-31b3300f-a78b-4d74-9b17-34f2c2c405fc.png)

2022-08-20 13:32 UTC, bxiiiiii commented on sdk/go-sdk/test/runtime/integrate_test.sh
>  go test -p 1 -v ./...
demo目录下很多结果都只是简单地打印出来，没有针对结果进行一下 assert 确保一致。两边的代码定位不太一样，用来演示和测试的代码存在一定差异，如果直接拿来用的话重叠的部分只需要保留一边的代码还是都保留呢

2022-08-20 13:40 UTC, seeflood commented on sdk/go-sdk/test/runtime/integrate_test.sh
>  go test -p 1 -v ./...
> demo目录下很多结果都只是简单地打印出来，没有针对结果进行一下 assert 确保一致。

demo 目录下的代码是建议加断言的，如果不满足断言就panic，比如：
![image](https://user-images.githubusercontent.com/26001097/185748755-b7eb166f-994e-4419-a0f2-c625a7af2928.png)

可能一些老代码没加panic，需要后续改掉

>两边的代码定位不太一样，用来演示和测试的代码存在一定差异，如果直接拿来用的话重叠的部分只需要保留一边的代码还是都保留呢

是的，两边定位不一样，在集成测试中可以既跑demo，又跑你新写的测试用例 `integrate_test.go` ，这样以后一些不适合放demo 里的 corner case 检查可以写在 `integrate_test.go`,而普通的case 写在 demo 里就行，就不用再在 `integrate_test.go` 里再写一遍了

2022-08-31 12:00 UTC, bxiiiiii commented on sdk/go-sdk/test/runtime/integrate_test.go
> +			stateKey = "/zookeeper"
@seeflood 测试里面zookeeper是本地跑的所以这个方法不太行。我之前的解决方法是在脚本里面新建znode
![1661947065388](https://user-images.githubusercontent.com/75570810/187673434-78a13e3e-23f2-4d08-8609-d6ef09611d80.jpg)
这个方法怎么样呢

2022-09-25 01:47 UTC, closed without merging

2022-09-25 07:36 UTC, bxiiiiii commented
@zhenjunMa @seeflood 
I accidentally closed this pr, you can check #795 .