docs: lock demo
mosn/layotto pull request #783
Opened 2022-09-11 13:40 UTC by akkw

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-09-23 09:48 UTC, seeflood requested changes

2022-09-23 09:48 UTC, seeflood commented on docs/zh/start/lock/start.md
> +```shell @if.not.exist examples-sequencer/target/examples-lock-1.2.0-SNAPSHOT-jar-with-dependencies.jar
This path is wrong

2022-09-26 06:55 UTC, seeflood approved these changes
lgtm. I modified some files. Thanks for your contribution!

2022-09-26 07:31 UTC, seeflood approved these changes
lgtm. I modified some files. Thanks for your contribution!

2022-09-26 07:44 UTC, zhenjunMa approved these changes

2022-09-26 07:44 UTC, merged