translate hot_to_generate_api_doc
mosn/layotto pull request #806
Opened 2022-10-01 14:25 UTC by pmupkin

translate the code-generator guide into chinese; 把代码生成器的使用文档翻译成中文 #797

2022-10-02 05:22 UTC, seeflood commented
@pmupkin Thanks! Please sign the CLA first

2022-10-03 01:23 UTC, pmupkin commented
OK，I have signed CLA.

2022-10-04 09:44 UTC, seeflood requested changes

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +假设你已经实现了一个新的proto文件`spec/proto/extension/v1/email/email.proto`，并且想在Layotto中实现这个API。
```suggestion
假设你写了一个新的proto文件 `spec/proto/extension/v1/email/email.proto`，并且想在Layotto中实现这个API。
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +// 不同的信息类型......
```suggestion
// 不同的 message 类型......
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
>  ```protobuf
```suggestion

```protobuf
```

add a blank line above it

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +- 如果你不想为proto生成sdk和sidecar，添加注释`/* @exclude skip code_generator */` 。
```suggestion
- 如果你不想为proto生成sdk和sidecar 代码，添加注释`/* @exclude skip code_generator */` 。
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +  - 快速入门文件（包括中文和英文）
```suggestion
  - quickstart 文档（包括中文和英文）
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +  - layotto sidecar
```suggestion
  - layotto sidecar 代码（实现了新的 API）
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +  - 更新的API参考列表
```suggestion
  - 自动更新 API 文档列表
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +  - 更新的侧边栏（该工具将把生成的快速入门文档添加到https://mosn.io/layotto 的侧边栏中）
```suggestion
  - 自动更新侧边栏（该工具将把生成的快速入门文档添加到https://mosn.io/layotto 的侧边栏中）
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +- 更新的CI（该工具将把生成的快速入门文档添加到CI脚本`etc/script/test-quickstart.sh`中）
```suggestion
- 自动更新 CI（该工具将把生成的快速入门文档添加到CI脚本`etc/script/test-quickstart.sh`中）
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +## 花絮
```suggestion
## 实现原理
```

2022-10-04 09:44 UTC, seeflood commented on docs/zh/api_reference/how_to_generate_api_doc.md
> +我们有一个叫做[protoc-gen-p6](https://github.com/seeflood/protoc-gen-p6)的protoc插件，主要为Layotto生成代码。
```suggestion
我们有一个叫做[protoc-gen-p6](https://github.com/seeflood/protoc-gen-p6)的protoc插件，用于为Layotto生成代码。 
```

2022-10-08 02:33 UTC, zhenjunMa approved these changes

2022-10-08 02:37 UTC, merged