feat: support nacos configstore component (level1)
mosn/layotto pull request #939
Opened 2023-06-07 16:52 UTC by cyb0225

**What this PR does**:

support nacos configstore component with level1.

**Which issue(s) this PR fixes**: #921

Fixes #

**Special notes for your reviewer**:

目前实现的是没有 tag 和 label 版本的，很快会加上。
且目前只是要 demo 里的 common 代码进行了简单测试，针对 nacos 组件的测试他没有提供官方 IP, 也没有找到像 redis,mysql 这样的开源 mock, 我可能需要先实现一份简单的 nacos mock, 再去实现这个单测。

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-06-16 04:29 UTC, cyb0225 commented
@wenxuwan, 大致功能已经做完了，你看看。还剩下几个地方可能需要再讨论一下。

2023-06-16 04:31 UTC, cyb0225 commented
> @wenxuwan, 大致功能已经做完了，你看看。还剩下几个地方可能需要再讨论一下。我直接加载代码的 review 里了。

2023-06-19 04:11 UTC, wenxuwan requested changes

2023-06-19 04:11 UTC, wenxuwan commented on components/configstores/nacos/config.go
> +	namespaceIdKey = "namespace_id"
The configuration in the metadata needs a document to explain it. Through the form of a table, let the user know what the configured key and the corresponding meaning are. The current demo only gives an example of app_name

2023-06-19 04:11 UTC, wenxuwan commented on components/configstores/nacos/configstore.go
> +		"clientConfig": cc,
The key should use constant.KEY_CLIENT_CONFIG defined in Nacos SDK

2023-06-19 07:53 UTC, wenxuwan commented on components/configstores/nacos/change_listener.go
> +type subscriberHolder struct {
直接用sync.Map吧，不需要定义subscriberHolder

2023-06-21 06:11 UTC, wenxuwan commented
@cyb0225 reviewer的cr的comments如果修复了，可以在comments下面回复个done之类的，然后reviewer可以继续cr，如果没问题了，reviewer才可以点
![image](https://github.com/mosn/layotto/assets/11661906/983060b8-8dbf-4de1-a20b-df696f8f932e)

2023-06-29 03:50 UTC, wenxuwan commented on components/configstores/nacos/default_logger_test.go
> +	logger.Error("test Debug")
这个应该是test Error

2023-06-29 04:02 UTC, wenxuwan commented on components/configstores/nacos/const.go
> +	defaultLogFileName = "nacos-sdk-log"
defaultLogFileName 改成 nacos-sdk.log吧

2023-06-29 04:26 UTC, wenxuwan commented
根据这个 https://mosn.io/layotto/#/zh/development/developing-component 文档，写个demo和快速开始文档再，🌹

2023-06-29 17:20 UTC, cyb0225 commented
> 根据这个 https://mosn.io/layotto/#/zh/development/developing-component 文档，写个demo和快速开始文档再，🌹

这个 ci 错误感觉可以忽略，因为我在代码里提前写了 nacos config 的路径，不过还没 merge 进去所以找不到。

quick start 我打算 merge 进去后，写一个 docker-compose，用新版的 layotto 重新提一个 pr，你看看怎么样。

2023-06-30 03:12 UTC, wenxuwan commented
> quick start 我打算 merge 进去后，写一个 docker-compose，用新版的 layotto 重新提一个 pr，你看看怎么样。

嗯，是可以忽略

2023-06-30 03:13 UTC, wenxuwan approved these changes

2023-06-30 03:13 UTC, merged

2023-06-30 03:13 UTC, wenxuwan approved these changes

2023-06-30 03:13 UTC, wenxuwan approved these changes
LGTM