feat: 更新钉群二维码,更改check配置文件,更新apollo,IP地址
mosn/layotto pull request #947
Opened 2023-06-09 02:39 UTC by zhaoxuanqing

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-06-09 13:14 UTC, seeflood requested changes

2023-06-09 13:14 UTC, seeflood commented on docs/zh/start/file/minio.md
> +您可以使用 Docker 启动本地MinIO服务, 参考[官方文档](https://www.minio.org.cn/docs/minio/container/index.html)
别用中国镜像站地址了，dead link checker 在墙外运行，估计在连接这个镜像站时被墙了。
改成minio官方文档的地址吧，  https://min.io/docs/minio/container/index.html

2023-06-09 13:14 UTC, seeflood commented on .github/dead_link_check_config.json
> +    301
aliveStatusCodes 不要加这些错误码吧。把异常当正常，dead link checker就没意义了

2023-06-12 06:26 UTC, zhenjunMa approved these changes

2023-06-12 06:29 UTC, merged

2023-06-13 11:45 UTC, seeflood commented on docs/zh/blog/code/webassembly/index.md
> +- [5] [云原生运行时的下一个五年](https://www.sofastack.tech/blog/the-next-five-years-of-cloud-native-runtime/)
@zhenjunMa @zhaoxuanqing 
这里把引文的4删了、把56改成了45，但是上文的引用没改，有问题:
![image](https://github.com/mosn/layotto/assets/26001097/e9328ac2-4e17-4590-af21-0eb00bfb46ca)

引文不用改吧，如果不需要被dead link checker扫描到，把这个url加进忽略列表里就行