encode dubbo two-way request with payload
mosn/layotto pull request #97
Opened 2021-06-25 03:11 UTC by MoonShining

**What this PR does**:

**Which issue(s) this PR fixes**:

assemble dubbo packet manually

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-06-25 06:19 UTC, wenxuwan commented
@carolove 可以一起帮忙看下, @MoonShining 的改动的话就是需要用户传过来的data是hession过的，可能并没有什么实用性，用户几本不会自己去直接调用hession进行序列化，本身hession支持的语言也很有限。这边最好的话是用户直接json传递一下参数，函数名这些信息，layotto可以直接帮忙序列化。如果是java应用或者golang这种成熟的dubbo框架，可能就直接代理一下包就可以了。老哥可以发表下自己的看法也。

2021-06-25 06:20 UTC, zhenjunMa requested changes

2021-06-25 06:20 UTC, zhenjunMa commented on components/rpc/invoker/mosn/transport_protocol/dubbo.go
> +	frame.Flag = 0xc2 // 110(req two-way not-hb) 00010(hessian2 serialize)
这里注释写清楚一点，看着是序列化只支持hessian2?   two-way  not-hb是啥意思？

2021-06-25 06:20 UTC, zhenjunMa commented on components/rpc/invoker/mosn/transport_protocol/dubbo_test.go
> +	directionBool := (dubboFrame.Flag & (1 << 7))
上面的flag都写死了，这个单测是不是没用？

2021-06-28 08:48 UTC, zhenjunMa commented on components/rpc/invoker/mosn/transport_protocol/dubbo.go
>  func (d *dubboProtocol) ToFrame(req *rpc.RPCRequest) api.XFrame {
我刚才看了下代码，这个ToFrame函数的调用处，生成的requestID是+1的，按照dubbo的规范应该改成+2？

2021-11-08 02:54 UTC, closed without merging